### ISSUE TITLE
Assigning g:gutentags_project_root_finder

### ISSUE THREAD

**Issue by thecontinium** [ludovicchabant/vim-gutentags#100]
I'm looking to assign g:gutentags_project_root_finder to my own function but can't get this to work. I am trying to use let g:gutentags_project_root_finder = function("MyFunction") but this is not allowed since a function reference must start with a capital letter or if it starts with g: the first letter must be a capital letter. Can you adilvise how I see this up correctly ?

I have raised a pull request as a suggested fix. #106 

Cheers

**Comment by ludovicchabant** [comment]
You're supposed to set that setting to the name of function, so `let g:gutentags_project_root_finder = "MyFunction"` should work?

**Comment by thecontinium** [comment]
Hi - thanks. Yes - realised the problem was with the fixes in the pull request you merged. With that pull request it works as you detail.

Cheers



Sent from my iPhone

On 27 Nov 2016, at 13:53, Ludovic Chabant <notifications@github.com<mailto:notifications@github.com>> wrote:


You're supposed to set that setting to the name of function, so let g:gutentags_project_root_finder = "MyFunction" should work?

**Comment by ludovicchabant** [comment]
Cool, thanks.
