### ISSUE TITLE
gutentags_file_list_command does not work

### ISSUE THREAD

**Issue by threewordphrase** [ludovicchabant/vim-gutentags#101]
All of my gutentag specific config in .vimrc:

`set statusline+=%{gutentags#statusline('[Generating...]')}`
`let g:gutentags_project_root = ['Gemfile', '.git']`
`let g:gutentags_file_list_command = {`
`                             \ 'markers': {`
`                                 \ 'Gemfile': "bundle show --paths",`
`                                 \ '.git': 'git ls-files',`
`                                 \ },`
`                             \ }`
let g:gutentags_define_advanced_commands=1`

Output with `GutentagsToggleTrace` set:

`"lib/attachment_file_migrator.rb" 65L, 1545C`
`gutentags: Scanning buffer 'lib/attachment_file_migrator.rb' for gutentags setup...`
`gutentags: Setting project type to ruby`
`gutentags: Setting gutentags for buffer 'lib/attachment_file_migrator.rb'`
`gutentags: Generating missing tags file: /Users/aaron/code/casebook2/tags`
`gutentags: Running: !/Users/aaron/.vim/bundle/vim-gutentags/plat/unix/update_tags.sh -e "ctags" -t "tags" -p "." -L "bundle show --paths" >"tags.log" 2>&1 &`
`gutentags: In:      /Users/aaron/code/casebook2`
`:!/Users/aaron/.vim/bundle/vim-gutentags/plat/unix/update_tags.sh -e "ctags" -t "tags" -p "." -L "bundle show --paths" >"tags.log" 2>&1 &  `

According to `man ctags` (installed on OSX with homebrew, Exuberant Ctags 5.8) -L takes filenames, not a command to get them.

Am I missing another option/setting somewhere? It seems as though the text of the command is being sent to ctags instead of a file list.

**Comment by ludovicchabant** [comment]
The text of the command is not being sent to `ctags`, it's being sent to the `update_tags.sh` script that Gutentags uses to manage running `ctags` and a whole bunch of other things. If you look at it you'll see that [it does indeed run the command](https://github.com/ludovicchabant/vim-gutentags/blob/master/plat/unix/update_tags.sh#L92), stores it in a temp file, and passes that temp file to `ctags`.

You can check that `tags.log` file for the output of the script, which will contain the exact `ctags` command line.

**Comment by berfarah** [comment]
I'm having an issue with `g:gutentags_file_list_command`, but not quite the same way.

Here are my steps to reproduce:

### Works
```sh
rg --files > tags.files
ctags -f tags.temp -L tags.files
# produces a 800K tags file that ignores gitignored directories
```

### Using gutentags

```sh
path/to/vim-gutentags/plat/unix/update_tags.sh -p "." -L 'rg --files'
# produces a 260MB tags file with gitignored directories
```

What it's doing is running:

```sh
ctags -f tags.temp -L tags.files "."
# if you see above, "." is added (the project directory)
```

When I run this command myself, I get the same result - it ignores the files provided via `-L` and instead runs on the entire project. I've tried this with both Exuberant Ctags and Universal Ctags and I'm getting the same result.

To fix, it seems like we'd need to remove the project directory being added at the end when a command is provided

**Comment by ludovicchabant** [comment]
We'll take the discussion over to the PR.
