### ISSUE TITLE
:GutentagsUpdate! results in a black screen

### ISSUE THREAD

**Issue by bstaletic** [ludovicchabant/vim-gutentags#102]
When I run `:GutentagsUpdate!` inside Vim it results in a black screen. Running `:GutentagsUpdate` works as intended. When I get the black screen everything seems to be functional, but nothing is displayed until a portion of the screen changes at which point that portion of the screen becomes visible. Running `vim -c 'GutentagsUpdate!' afile.c` does display the file properly.
Version of ctags:
```
Universal Ctags 0.0.0(a04d4da), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Nov 12 2016, 22:24:19
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +option-directory, +coproc, +xpath
```
I have also tried exuberant-ctags instead of universal-ctags, but it made no difference.

I've also seen [#47](https://github.com/ludovicchabant/vim-gutentags/issues/47), but I don't see anything useful to be done. Perhaps I'm missing something.

**Comment by bstaletic** [comment]
This is actually an expected behaviour. If anyone runs into this issue, just run `:redraw!` after it.

**Comment by justinmk** [comment]
Or use Neovim, which doesn't have this problem.

**Comment by ludovicchabant** [comment]
What version of Vim are you using? I've never seen `GutentagsUpdate!` result in a black screen before.

**Comment by bstaletic** [comment]
I tried it on two completely different setups with two different versions of Vim. One is my personal setup and the version is 8.0.0056 while the other is my friends setup used at his work place, so I can't check his version, but I believe it is 7.4.

Here's what Vim's various.txt says:
```
                          Vim redraws the screen after the command is finished,
                          because it may have printed any text.  This requires a
                          hit-enter prompt, so that you can read any messages.
                          To avoid this use:
                                  :silent !{cmd}
                          The screen is not redrawn then, thus you have to use
                          CTRL-L or ":redraw!" if the command did display
                          something.
```
