### ISSUE TITLE
"E426: tag not found" after write.

### ISSUE THREAD

**Issue by pseewald** [ludovicchabant/vim-gutentags#107]
I'm using vim-gutentags with the project [CP2K](https://github.com/cp2k/cp2k). Everything works fine after opening a file, but as soon as I type `:w`, Vim can not find any tags. I use vim-gutentags with default settings and Exuberant Ctags. I could not reproduce this error with any other project, so I'm giving instructions how to reproduce it with CP2K:

1. git clone https://github.com/cp2k/cp2k.git
2. cd cp2k/cp2k/src/
3. open an arbitrary file with vim, and go to the definition of an arbitrary tag with `CTRL-]`. This should work fine
4. if step 3 works, go back with `CTRL-t`
5. now save `:w`, and type again `CTRL-]`. This should trigger the error `E426: tag not found`

Let me know if you need me to test anything.

**Comment by ludovicchabant** [comment]
Hi!

It _mostly_ works for me... I was able to go to a definition (step 3), go back (step 4), save and go to the definition again (step 5). I was also able to create a new sub-routine, save the file, and check that the tags file now contained it. I renamed it, saved the file, and check that the new name was there too. So it seems to work AFAICT. Some symbols couldn't be found though, like `section_create`, for which Vim told me `tag not found`, but I don't know if that function is defined in that code base?

It would be that when you save, something goes wrong when the tags file gets regenerated? Use `let g:gutentags_trace = 1` before saving the file. It will show you what's going on, and the regeneration script will log a file whose path you'll see in the output. You can then check if something went wrong there. If it looks legit, you'll have the command line so you can re-run `ctags` yourself and see if it's OK.

**Comment by pseewald** [comment]
Hi,

Thanks for the hints. By testing the commands in the log file, I could find that the `--append` option of ctags is the problem: for some reason, this removes almost all tags in the tag file (the new tags of the specified file are missing as well). So for sure, something is wrong with my ctags and this is not an issue of vim-gutentags.

**Comment by pseewald** [comment]
Just for the record: I found that using Universal Ctags instead of Exuberant Ctags solves the issue.
