### ISSUE TITLE
ctags running in home directory recursively

### ISSUE THREAD

**Issue by junkblocker** [ludovicchabant/vim-gutentags#111]
With some recent update to gutentags it seems ctags (Universal Ctags) starts running in my home directory taking a lot of CPU/time as soon as I even open a blank MacVim instance. It doesn't seem like this used to be the case before. Yes, I do have a tags file in there but I'd expected tag generation only for the current file, only when a file is saved. Is this a regression or am I dreaming?

**Comment by ludovicchabant** [comment]
You may be dreaming :)

Gutentags has always triggered a (re)generation of the `tags` file when you open a file inside a "known project" for the first time in the current session (assuming `g:gutentags_generate_on_new` is set to `1`, which is the default). After that first time, it will only regenerate when you save. Maybe you changed that setting?

**Comment by junkblocker** [comment]
What is considered a 'known project'? In my dreams it never used to index my complete home directory recursively even though I've always had a tags file there before. No I haven't changed anything other than upgrade gutentags when I wrote this bug.

**Comment by junkblocker** [comment]
I think part of the reason may be the buffers option (which it not recent in my config either)

```viml
set sessionoptions=blank,buffers,folds,resize,tabpages,winpos,winsize
```

which loads buffers from previous session. However that still doesn't explain the following on me just opening MacVim

```sh
% pgrep ctags
88166 /bin/sh /Users/xxxx/.vim/neobundles/vim-gutentags/plat/unix/update_tags.sh -e ctags -t tags -p . -o /Users/xxxx/.vim/neobundles/vim-gutentags/res/ctags_recursive.options -x *.bak -x *~ -x *.o -x *.obj -x *.swp -x *.class -x *.pyc -x .DS_Store -x .hg -x .svn -x .git
88167 ctags -f tags.temp --options=/Users/xxxx/.vim/neobundles/vim-gutentags/res/ctags_recursive.options --exclude=*.bak --exclude=*~ --exclude=*.o --exclude=*.obj --exclude=*.swp --exclude=*.class --exclude=*.pyc --exclude=.DS_Store --exclude=.hg --exclude=.svn --exclude=.git .
```

**Comment by ludovicchabant** [comment]
Oh actually I found out what's going on. I'm not sure if it has always been like that or not, but when you open Vim, it usually opens an empty buffer (that `[No Name]` buffer). Now Gutentags still checks whether it should start working on it, and takes it path (an empty string) and expands it to a full path (which Vim returns as the current working dir) and then looks for root markers.

So if you happen to start Vim with the current working dir set inside of a project, Gutentags will start indexing that project right away!

One way I can imagine to fix it would be to check for an empty string buffer name [somewhere around here](https://github.com/ludovicchabant/vim-gutentags/blob/master/autoload/gutentags.vim#L202) but I'm not sure if that would catch other situations than this one... maybe you can give it a try and see if anything else breaks?

**Comment by ludovicchabant** [comment]
Something like this:

```
    if expand('%') == ''
        return
    endif
```

**Comment by junkblocker** [comment]
That does handle the new instance case, thanks.

Is there a way to turn off recursive adding completely? I want files added only individually. My desired setup is

```
$HOME/some/dir/loose/taggable.file   # This should only get added to $HOME/tags, which should get created/updates on editing this file with tags for only this file if not present
$HOME/another/dir/symlinked_file -> $HOME/some/git/repo/symlinkable_file  # Editing this should create/update $HOME/some/git/repo/tags not $HOME/tags
$HOME/some/git/repo/.git/
$HOME/some/git/repo/symlinkable_file
$HOME/some/git/repo/and/more_symlinkable_file
$HOME/some/git/repo/tags
```

**Comment by ludovicchabant** [comment]
The fix I mentioned has made it into Gutentags by the way.

I'm not sure what you mean by "recursive adding"? By default, Gutentags passes the `-R` flag to `ctags`, which will make it index everything inside a directory -- if that's what you mean. In order to customize this, you could set the `g:gutentags_file_list_command` to something that will generate the exact list of files you want `ctags` to index... is that what you're looking for?

**Comment by junkblocker** [comment]
Can I have it index/update the tags for just the current file being saved? It's idea of -R 's scope is too broad. At the very least I want to restrict it to the repo for the current file and never to do -R if it can't locate repo top (i.e. never do -R in home directory). If this turns out to be too much I think I'll need to revive  my own changes to the autotag plugin and use that.

**Comment by ludovicchabant** [comment]
You can override the `-R/--recurse` that comes from core Gutentags by specifying `--recurse=no` in either `g:gutentags_ctags_extra_args`, or in the project's `.gutctags` file.
