### ISSUE TITLE
Undocumented Vim version dependency?

### ISSUE THREAD

**Issue by pneisen** [ludovicchabant/vim-gutentags#118]
Running on Ubuntu 14.04.3 and Vim 7.4, I get the following error when writing a .go file:
```
Error detected while processing function <SNR>81_write_triggered_update_tags[3]..<SNR>81_update_tags[31]..gutentags#pwd:
line    4:
E118: Too many arguments for function: getcwd
E15: Invalid expression: haslocaldir() ? getcwd(0, 0) : getcwd()
Error detected while processing function <SNR>81_write_triggered_update_tags[3]..<SNR>81_update_tags[41]..gutentags#chdir:
line    6:
E344: Can't find directory "0" in cdpath
E472: Command failed
Error detected while processing function <SNR>81_write_triggered_update_tags:
line    3:
E170: Missing :endfor
```
The tags were also not found by Vim.

Upgrading to Vim 8.0, fixes the problem and tags now work. I assume there is an undocumented Vim version dependency?

**Comment by rafi** [comment]
@hkupty FYI

**Comment by hkupty** [comment]
Sorry for taking long to answer.. I'll take a look at it. 

Cheers

**Comment by ludovicchabant** [comment]
Ah yes it looks like we need to add a check for Patch 7.4.1126, which is when `getcwd` got the new arguments.

**Comment by hkupty** [comment]
@ludovicchabant sure.. I'll add that

**Comment by ludovicchabant** [comment]
I think the merging of PR https://github.com/ludovicchabant/vim-gutentags/pull/117 fixed this?

**Comment by pneisen** [comment]
@ludovicchabant Looks like it did. I was able to use this plugin while running Vim 7.4. Thanks!
