### ISSUE TITLE
Fully regenerate tags after `git pull`

### ISSUE THREAD

**Issue by zackhsi** [ludovicchabant/vim-gutentags#119]
Hey! First off, great project. Thank you very much.

I have a feature request :)

My tags file gets out of date when:
1. Clone repository, open file, generate tags for whole project. (I read https://github.com/ludovicchabant/vim-gutentags/issues/59, `g:gutentags_generate_on_new` may be relevant).
2. Wait some period of time while other people push code upstream.
3. `git pull` the code down. Many files are updated.
4. Browse project, and tags are out of date. Saving an individual file will refresh the tags for that one file, but this does not scale to the whole project.

What I would like to have happen is that gutentags realizes that a git pull happened, maybe looks at the files changed since the tags file was last updated, and gets the tags file to be fully in sync.

The current workaround is to `rm` the tags file. This is fine, but not ideal.

Thanks again.

**Comment by ludovicchabant** [comment]
Hi! Thanks!

1. Yes, `g:gutentags_generate_on_new` will solve that situation.

4. Yep, tags go out of date in that case. I personally have a mapping to `:GutentagsUpdate!` to force regenerate the tags file (no need to `rm` it), which I use after a pull/merge/branch change/whatever.

The reality here is that I haven't thought of a good, solid way to detect these things -- especially when you consider that Git is not the only use case to handle (I personally spend most of my time in Mercurial and Perforce). I'm open to suggestions!

**Comment by zackhsi** [comment]
Okay, I have done the same now :)

This is definitely a complex problem, and hard to solve "while staying completely out of your way".

Running `:GutentagsUpdate!` on a large project definitely gets in the way, but for a smaller project may be acceptable. There could be a default project size (ignoring VCS, etc.) under which an automatic `Update!` could be seen as "magic" and not cumbersome :)

Just idle thoughts... for now, I will use the mapping.

Thanks again!
