### ISSUE TITLE
cscope/codesearch support 

### ISSUE THREAD

**Issue by jonthn** [ludovicchabant/vim-gutentags#12]
Would it be possible or make sense to provide support for other tools that indexes the code.
I'm mainly thinking about cscope which as builtin support in Vim.
But it could be extended to tools like : https://github.com/junkblocker/codesearch

**Comment by ludovicchabant** [comment]
Hi there! It would indeed make sense to support stuff like `cscope`, but frankly it's not going to happen any time soon unless someone submits a patch for it. I'm personally not using `cscope` or anything else, so until I do I wouldn't spend time and energy towards that, sorry. But if you or someone wants to work on it, I'll be happy to provide support and help with refactoring the existing code!
