### ISSUE TITLE
gutentags changes to home directory on BufWritePost

### ISSUE THREAD

**Issue by ZyX-I** [ludovicchabant/vim-gutentags#120]
At af7132f1bf89f18a69481b9fe5103c96c4248b9b `gutentags#pwd` uses `getcwd(0, 0)` if `haslocaldir()`. This call *always* returns an empty string, meaning that directory changes to the home directory when trying to restore it: tab page number zero does not have the expected meaning. You should remove the second argument completely, or supply `tabpagenr()` there instead.

**Comment by ZyX-I** [comment]
Using vim-8.0.348.

**Comment by rafi** [comment]
@ZyX-I I was having a similar issue and seems that #117 fixes it, please try it.

**Comment by mikedfunk** [comment]
I used this fork to see if it fixed the cd issue and it did not. Vim config:
```
    Plug 'hkupty/vim-gutentags', { 'branch': 'new-fix-tcd' }
```
When I save it still cds to $HOME... sometimes.

**Comment by hkupty** [comment]
@mikedfunk I'll investigate that.. I'm also having problems with cd/tcd and I think vim-fzf has something to do with it.

**Comment by jamessan** [comment]
The simple fix is to just replace `getcwd(0, 0)` with `getcwd()`.  `haslocaldir()` (with no arguments) reports whether the current window has a local directory and `getcwd()` also acts on the current window.

**Comment by hkupty** [comment]
`getcwd(0, 0)` works for neovim, so I think the proposed change is the following, right @jamessan 
```diff
   if has('nvim')
     return haslocaldir() ? getcwd(0, 0) : haslocaldir(-1, 0) ? getcwd(-1, 0) : getcwd()
   else
-    return haslocaldir() ? getcwd(0, 0) : getcwd()
+    return getcwd()
   endif
 endfunction
```

I can add that on #117

**Comment by jamessan** [comment]
`getcwd()` works for both vim and nvim, so you could probably just simplify it to

```vim
let wd = getcwd()
if has('nvim') && !haslocaldir() && haslocaldir(-1, 0)
  let wd = getcwd(-1, 0)
endif
return wd
```

**Comment by ludovicchabant** [comment]
I'm not sure about the NeoVim version, but wouldn't a simple fix be to change `getcwd(0, 0)` with `getcwd(winnr(), tabpagenr())`? It looks like passing `0` is the wrong thing here.

**Comment by jamessan** [comment]
Actually, all of this is overthinking things.  `getcwd()` always returns the effective working directory.  If there's a window-local working directory, it will be returned.  If not and you're using nvim, then a tab-local working directory will be returned.  Otherwise the global working directory is returned.

So the simple answer is to just use `getcwd()`.

**Comment by hkupty** [comment]
@jamessan that might make sense.. However, we still need to take care not to override buffer/tab/global cwd settings.

**Comment by ludovicchabant** [comment]
I think the merging of PR https://github.com/ludovicchabant/vim-gutentags/pull/117 would fix this since, among a couple other things, it reverted back to using `getcwd()`?

**Comment by ludovicchabant** [comment]
Closing old issues -- I think this one was fixed anyway.
