### ISSUE TITLE
Absolute path

### ISSUE THREAD

**Issue by sphynx79** [ludovicchabant/vim-gutentags#124]
When use your plugin in tag file i have absolute path, but i want relative path.
When open vim i set working directory the root of my project:
ex:
 project
         .git
         folder1
         folder2
         myfile.rb

open vim => cd project
but in tag file i have absolute path

This is my ctags --vserion
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Mar 10 2017, 13:33:34
  URL: https://ctags.io/
  Optional compiled features: +win32, +wildcards, +regex, +internal-sort, +multibyte, +case-insensitive-filenames

and this is my .ctags file
--recurse=yes
--tag-relative=yes
--exclude=.git
--exclude=.rblcl
--exclude=test
--fields=+lnKs

In terminal:
cd project
ctags.exe -R

work and generate tags file with relative path.

in my vimrc
function! Gentag()
   call system('ctags.exe ')
endfunction
command! Gentag :call Gentag()

also this work generate relative path inside my tags file

**Comment by ludovicchabant** [comment]
Ah yes, sorry about that, I introduced that bug a few weeks ago. Try syncing past e220e9b07b55dae8e4f75a4393b8474ef46112bf.

**Comment by sphynx79** [comment]
Thanks

2017-03-24 1:41 GMT+01:00 Ludovic Chabant <notifications@github.com>:
