### ISSUE TITLE
No gutentags support for this buffer.

### ISSUE THREAD

**Issue by neilpeter08** [ludovicchabant/vim-gutentags#125]
My gutentags is not generating any tags and when i ran `:GutentagsToggleTrace` it prints out a message like this

```
gutentags: Scanning buffer 'some_file.rb' for gutentags setup...
Press ENTER or type command to continue
gutentags: No gutentags support for this buffer.
Press ENTER or type command to continue
```

**Comment by neilpeter08** [comment]
nvm, managed to make it work

**Comment by koblihh** [comment]
@neilgarcia -- May I ask how did you resolve your issue at last?

I cannot seem to find a proper solution to make it work on my end.

Error message.
```
gutentags: Tracing is enabled.
gutentags: Scanning buffer '~\_vimrc' for gutentags setup...
gutentags: No gutentags support for this buffer.
```

Plugin configurations.
```
let g:gutentags_cache_dir = g:vim_dir . '/tags'
let g:gutentags_define_advanced_commands = 1
let g:gutentags_project_root = ['tags']
```

Any suggestions / help will be greatly appreciated!

**Comment by ludovicchabant** [comment]
FYI, @koblihh, Gutentags prints this "No gutentags support for this buffer" message when it can't find any project root marker.
