### ISSUE TITLE
# in filenames with neovim (vim8 is fine)

### ISSUE THREAD

**Issue by CookiesBestDinner** [ludovicchabant/vim-gutentags#127]
```
blah#" [New] 0L, 0C written                                                                              
Error detected while processing function <SNR>138_write_triggered_update_tags[3]..<SNR>138_update_tags[34]
..gutentags#ctags#generate:                                                                               
line  112:                                                                                                
E194: No alternate file name to substitute for '#': !/home/nate/.vim/plugged/vim-gutentags/plat/unix/updat
e_tags.sh -e "ctags" -t "/tmp/blah/.tags" -p "/tmp/blah" -s "/tmp/blah/blah#" -o "/home/nate/.vim/plugged/
vim-gutentags/res/ctags_recursive.options" -x '*/node_modules/*' -x '*/elm-stuff/*' -x "*/node_modules/*" 
-x "*/elm-stuff/*" -x "*/dist/*" >/dev/null 2>&1 &                                                        
Error detected while processing function <SNR>138_write_triggered_update_tags:                            
line    3:                                                                                                
E170: Missing :endfor                                                                                     
Press ENTER or type command to continue                                                           
```

Reproducing the above error:

```
$ mkdir /tmp/blah
$ cd /tmp/blah
$ git init
$ nvim blah# +w  # save a file with # in it
```

gutentags 855a01f
neovim 0.1.7

My gutentags version includes #110 which looks like the same-ish issue

**Comment by justinmk** [comment]
When you tested on vim8, perhaps it only worked because `@#` was non-empty? (i.e., you happened to have an alternate file)

**Comment by CookiesBestDinner** [comment]
Not following. How do I test that?

**Comment by justinmk** [comment]
If `:echo @#` shows a file name, it's not empty.

**Comment by CookiesBestDinner** [comment]
Typing in `:echo @#` doesn't show anything either vim implementation when running them without a file argument. (No clue what I'm looking for or if I tested that like you wanted though)

**Comment by justinmk** [comment]
Ok, seems that my guess was wrong. Nevertheless, gutentags should escape `#` (and `%`) in calls to `:!`.

**Comment by ludovicchabant** [comment]
I'm confused, where should we be escaping special characters? The only thing relevant near where the error gets thrown is a call to `fnamemodify`, which accepts characters like `#` without any problem.

**Comment by justinmk** [comment]
>  where should we be escaping special characters? 

line 112 of `gutentags#ctags#generate()`

>  The only thing relevant near where the error gets thrown is a call to fnamemodify, which accepts characters like # without any problem.

line 112 of `gutentags#ctags#generate` is a call to `silent execute l:cmd`

**Comment by ludovicchabant** [comment]
This doesn't seem to apply anymore now that we run commands through the job API.
