### ISSUE TITLE
Feature request: Optionally generate / load tags files when vim is started in a project with an empty buffer

### ISSUE THREAD

**Issue by smkent** [ludovicchabant/vim-gutentags#130]
Previously, Gutentags would generate and/or load the tags file for the current project when Vim was started in a project directory with no file. This behavior was removed in e89fc38ce9c19b2ed870b0a67fcec8bfaceeb15f.

Being able to run `vim` with no arguments and immediately start searching my tags was an extremely useful feature. I frequently start Vim in a project just so I can start searching my tags using [ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim). Since Gutentags no longer generates / loads the tags file when Vim starts with an empty buffer, I now have to start Vim on an existing file within a project in order to load that project's tags file.

It would be nice if this behavior were restored or provided as an option.

**Comment by ludovicchabant** [comment]
Cool, I just added it as `g:gutentags_generate_on_empty_buffer` (see cfd64e0d9501dfb820c54e6feeedba6c2b7b6777).

**Comment by smkent** [comment]
This works great, thank you!
