### ISSUE TITLE
installed but not loading

### ISSUE THREAD

**Issue by alanhamlett** [ludovicchabant/vim-gutentags#131]
Installed vim-gutentags using Vundle, and have the plugin set to load in my vimrc with `Plugin 'ludovicchabant/vim-gutentags'`, but there aren't any commands available and no ctags are generated.

For example, trying to run `:GutentagsUpdate` results in this error:
`E492: Not an editor command: GutentagsUpdate`

Does vim-gutentags not work with Vundle?

**Comment by dmitry-saritasa** [comment]
I have the same issue, but have no idea how to use this. I.e. It seems my tags are being generated.

**Comment by alanhamlett** [comment]
It works for me now, I had accidentally `:PluginClean`ed/deleted the plugin but re-installed and it works as expected.
