### ISSUE TITLE
Undefined variable g:gutentags_modules

### ISSUE THREAD

**Issue by fredmcfly** [ludovicchabant/vim-gutentags#133]
Error occurs every time I open gVim regardless of what file I open.

`Error detected while processing C:\Users\UserName\vimfiles\plugin\vim-
gutentags\autoload\gutentags.vim:
line  307:
E121: Undefined variable: g:gutentags_modules
E15: Invalid expression: g:gutentags_modules
Error detected while processing function gutentags#get_plat_file:
line    1:
E121: Undefined variable: g:gutentags_plat_dir
E15: Invalid expression: g:gutentags_plat_dir . a:filename . g:gutentags_script_ext
E121: Undefined variable: g:gutentags_plat_dir
E15: Invalid expression: g:gutentags_plat_dir . a:filename . g:gutentags_script_ext
E121: Undefined variable: g:gutentags_plat_dir
E15: Invalid expression: g:gutentags_plat_dir . a:filename . g:gutentags_script_ext
E121: Undefined variable: g:gutentags_plat_dir
E15: Invalid expression: g:gutentags_plat_dir . a:filename . g:gutentags_script_ext

Error detected while processing C:\Users\UserName\vimfiles\plugin\vim-gutentags\autoload\gutentags.vim:
line  307:
E121: Undefined variable: g:gutentags_modules
E15: Invalid expression: g:gutentags_modules`

I am using Windows 10, VIM 8.0 for MS-Windows 32-bit GUI version.
I am also using vim-plug as my plugin manager and have the latest version of gutentags.
I have install exuberant-ctags 5.8 and is found in my PATH.

**Comment by ludovicchabant** [comment]
Hi! Sorry about that.

Can you check what you get if you type `:echo &cp` and `:echo g:gutentags_dont_load` ?

**Comment by fredmcfly** [comment]
:echo &cp returns 0

:echo g:gutentags_dont_load returns ->

E121 Undefined variable: g:gutentags_dont_load
E15 Invalid expression: g:gutentags_dont_load

**Comment by ludovicchabant** [comment]
Mmmh I frankly have no idea what's up... if you open Vim without any file (empty buffer) and type `echo g:gutentags_modules`, do you get anything? (you should get `['ctags']`).

**Comment by ludovicchabant** [comment]
Closing old issues.
