### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by dmitry-saritasa** [ludovicchabant/vim-gutentags#134]
installed with Vundle, can you pls explain what commands are available to navigate through tags?

**Comment by ludovicchabant** [comment]
Navigating through tags is done with the normal Vim commands for that -- Gutentags doesn't add anything there, as its goal is only to generate the tags file and keep it up to date.

Navigating through tags is mostly done with `CTRL+]`, and jump back with `CTRL+T`. See `:help tags` to get all the info.
