### ISSUE TITLE
"Command not found" error when opening a file

### ISSUE THREAD

**Issue by parisologist** [ludovicchabant/vim-gutentags#14]
Just installed the plugin, and opened up a java file in a project i'm working on. I get this error immediately (before the file loads):

Error detected while processing function <SNR>26_setup_gutentags..<SNR>26_update_tags:
line   74:
E371: Command not found
Error detected while processing function <SNR>26_setup_gutentags:
line   42:
E171: Missing :endif

**Comment by ludovicchabant** [comment]
Did you install `ctags`, and is it in your `PATH`?

**Comment by parisologist** [comment]
Yep! If I go to a command prompt to C: and type "ctags" I get "ctags: no files specified". So it's on my path.

**Comment by ludovicchabant** [comment]
Can you set `g:gutentrace_trace` to `1` in your `vimrc`, or run `:GutentagsToggleTrace`?

It should start spamming you with messages when it does something. This way, you can see exactly what command line it's running, and you can check stuff is OK. It will also output a `<tagfile name>.log` file next to the tags file, so you can also see any problem coming from inside the update script. You can post the results here if there's nothing obvious.

**Comment by parisologist** [comment]
Nothing much illuminating here...all the paths are correct (in particular the location of `C:\home\config\vimfiles\plat\win32\update_tags.cmd` is correct. Weird.

        gutentags: Scanning buffer 'C:\home\projects\turnstile\core\src\com\agencyport\turnstile\Turnstile.java' for gutentags setup...
        gutentags: Setting gutentags for buffer 'C:\home\projects\turnstile\core\src\com\agencyport\turnstile\Turnstile.java' with tagfile: C:\home\projects\turnstile\core\tags
        gutentags: Generating missing tags file: C:\home\projects\turnstile\core\tags
        gutentags: Running: !start /b C:\home\config\vimfiles\plat\win32\update_tags.cmd -e "ctags" -t "C:\home\projects\turnstile\core\tags" -p "C:\home\projects\turnstile\core" -l "C:\home\projects\turnstile\core\tags.log"
        gutentags: In:      C:\home\projects\turnstile\core
        :!start /b C:\home\config\vimfiles\plat\win32\update_tags.cmd -e "ctags" -t "C:\home\projects\turnstile\core\tags" -p "C:\home\projects\turnstile\core" -l "C:\home\projects\turnstile\core\tags.log"

        
        Error detected while processing function <SNR>26_setup_gutentags..<SNR>26_update_tags:
        line   76:
        E371: Command not found
        Error detected while processing function <SNR>26_setup_gutentags:
        line   42:
        E171: Missing :endif

**Comment by parisologist** [comment]
Also `C:\home\config\vimfiles\plat\win32\update_tags.cmd -e "ctags" -t "C:\home\projects\turnstile\core\tags" -p "C:\home\projects\turnstile\core" -l "C:\home\projects\turnstile\core\tags.log"` (which I cut and pasted from the "start" command above), when run on the command line, does indeed generate  a tags file for the project.

**Comment by parisologist** [comment]
Aha! It was a bug in Vim. I was on version 7.3.46; grabbing the latest (7.4) and the problem went away.

**Comment by ludovicchabant** [comment]
Interesting... I'll reopen this to remember to add a version check to the plugin, then. Thanks!
