### ISSUE TITLE
Error: Gutentags offers no command except :GutentagsUnlock

### ISSUE THREAD

**Issue by dropTableUsers42** [ludovicchabant/vim-gutentags#142]
I am using gvim in windows. Gutentags neither updates the ctags file, nor does it offer any other command or variable except :GutentagsUnlock

Note that the project that I am working on is not on git, so gutentags didn't generate a tags file, which i did myself at the root directory of the project by ctags -R in the command line.

**Comment by mo0z** [comment]
Hi, same problem here. I have only the command :GutenTagsUnlock.

**Comment by ludovicchabant** [comment]
If none of the other commands are defined, it means Gutentags didn't find any project to generate anything for. By default, Gutentags looks for a Git/Hg/Svn/etc. repository. If you're not working out of a repository, you'll have to tell Gutentags what defines a "project" in your case. See `g:gutentags_project_root`.
