### ISSUE TITLE
Files in the project directory that start with a hypen are parsed as options

### ISSUE THREAD

**Issue by tbodt** [ludovicchabant/vim-gutentags#147]
Not sure what the correct solution would be. The man page for ctags doesn't specify any way to escape such files.

**Comment by justinmk** [comment]
In most shell commands these days it is standard for `--` to declare the beginning of non-options.

**Comment by tbodt** [comment]
Hmm, putting -- at the top of the file might work.

~Theodore

**Comment by ludovicchabant** [comment]
Closing old issues. Besides, ctags doesn't seem to support files with hyphens at the start, and doesn't support `--` for indicating remaining file arguments (at least not with a recent Universal Ctags).
