### ISSUE TITLE
Simple Java Project

### ISSUE THREAD

**Issue by fantomius991** [ludovicchabant/vim-gutentags#148]
Hi all,

I have a simple Java Project (I use eclim) and I want to use vim-gutentags for this one. How can I create tag files for only directories of the project ? The tree of directories is : 

ProjectName --> bin, src, .classpath, .project
src --> *.java

P.S. I don't use git ...
Thanks !

**Comment by ludovicchabant** [comment]
Sorry I guess I never replied to this! :(
Gutentags will only create one `tags` file for the entire project -- and to skip some directories, there are some exclusion arguments that can be passed to `ctags`.
