### ISSUE TITLE
Git checkout hook?

### ISSUE THREAD

**Issue by jesseleite** [ludovicchabant/vim-gutentags#153]
If I checkout a colleague's branch, I'd love to regenerate ctags using a git post-checkout hook.  Is it safe to do this, if I open vim and gutentags starts doing it's thing with tags.lock and tags.temp?  Curious what the best way to implement post-checkout hook would be?

**Comment by ludovicchabant** [comment]
I'm not sure either :)

If you do the git checkout using Vim (like, say, with `fugitive`), you could probably just run `:GutentagsUpdate!` after that through some auto-command or mapping. If you run `git checkout` externally, however... I don't know. I guess you could look at trying to detect that the `HEAD` changed when Vim gets its focus back (`FocusGained`), and if so, also run `:GutentagsUpdate!` (so _not_ in a post-checkout hook, basically).

**Comment by ludovicchabant** [comment]
Closing old issues.
