### ISSUE TITLE
Current position wrong after a define inside functions

### ISSUE THREAD

**Issue by barisione** [ludovicchabant/vim-gutentags#154]
I have this code:

```
#include <stdio.h>

int main(int argc,
         char **argv)
{
    printf("Hello world!\n");

#define GREET(name) ("Hello " #name)

    printf("%s!\n", GREET(Marco));

    return 0;
}
```

Which generates this `tags` file:
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/4a06dc9/
GREET	test-tags.c	/^#define GREET(/;"	d	file:
main	test-tags.c	/^int main(int argc,$/;"	f	typeref:typename:int
```

The `tags` file look correct to me, but, if you go to the last `printf`, then gutentags thinks we are inside the `GREET` macro as it doesn't understand that it's just a define.

Is this a limitation of ctags as it doesn't have a way of saying where a function/define ends or is it a problem with gutentags?

**Comment by ludovicchabant** [comment]
What do you mean by "_then gutentags thinks we are inside the `GREET` macro_"?

Either way, it does look indeed like a `ctags` problem -- Gutentags just runs `ctags` to get the `tags` file, and Vim uses the `tags` file. Gutentags is really just a glorified batch script runner.

**Comment by ludovicchabant** [comment]
Closing old issues.
