### ISSUE TITLE
Help: Print Tags For Buffer

### ISSUE THREAD

**Issue by weilbith** [ludovicchabant/vim-gutentags#159]
Hey,
I rly like gutentags for managing my tags easily. It is fast, run automatically in the background and works well with projects. But when I'm working I like to have an overview (outline) for the current file I'm working in. Other features like a preview window and so on are nice as well. Cause this is/should not be a feature of gutentags, I tend to use tagbar. It's qualities are in display the tags and provide visual support. But as stated on their documentation it does not manage tag files. This is horrible, cause verytime I enter a project it needs quite long till I can start working. And this for every new buffer I open.<br>
So by the unix motto I won't to concatenate two applications, which are both the best on their specific task. I start reading the implementation from tagbar and gutentags to get a feeling how to get this work, that tagbar use the tagfiles generated by gutentags. I registered that gutentags set some variables/... to the buffers. Cause I'm still learning vimscript I couldn't find out if it is possible to get all tags for a specific buffer as return. So imagine a function I can call from tagbar to get this tags instead of letting tagbar calling ctags itself everytime. <br>
Hopefully anyone understand what my actual question is. :'D
Thanks for ur help!

**Comment by ludovicchabant** [comment]
Hi there, thanks for the kind words!

I also use Tagbar, and I don't see what the problem is? Tagbar will always just run `ctags` on the current file, so it's always very fast, regardless of the size of the codebase... so I don't really understand what your use-case and problem are?

**Comment by weilbith** [comment]
Rly? So _tagbar_ can reuse _gutentags_ generated tags and don't have to generate them on its own?
