### ISSUE TITLE
Ignoring folders defined in .gitignore

### ISSUE THREAD

**Issue by samaursa** [ludovicchabant/vim-gutentags#161]
Is it possible to ignore files/folders defined in a `.gitignore`? I tried searching if this is already supported or already asked but it doesn't seem to be the case.

ctags already supports something similar with the `--exclude=@.gitignore` pattern.

**Comment by ludovicchabant** [comment]
There's no feature in Gutentags to do this per se (most of my projects ignore files that I _do_ want to include in tags generation), but if there's some argument you can pass to `ctags` to make it do what you want, you can look at either a `.gutctags` file in your project root to pass project-specific `ctags` parameters, or a global `g:gutentags_ctags_extra_args` (which sadly isn't documented yet, I'll fix that).

**Comment by samaursa** [comment]
Thanks @ludovicchabant. 

I did not look at `.gutctags` or `g:gutentags_ctags_extra_args`. I will look at the argument more closely. Although `ctags` itself doesn't have a feature to ignore files found in `.gitignore`: https://github.com/universal-ctags/ctags/issues/218

I was able to find the following solution however:

```
let g:gutentags_file_list_command = 'rg --files'
```

which works very well.

**Comment by ludovicchabant** [comment]
Cool, thanks for the tip!

**Comment by enting-rogers** [comment]
If you want to check if `rg` is available to make it portable, here you go:
```
if executable('rg')
  let g:gutentags_file_list_command = 'rg --files'
endif
```

**Comment by rockandska** [comment]
For people who do not use `ag`, I use this config :
```
let g:gutentags_file_list_command = {
      \ 'markers': {
      \ '.git': '{ git ls-files; git ls-files --others --exclude-standard; }',
      \ },
      \ }
```
It allows having :
- git tracked files
- git untracked files with .gitignore files/dirs excluded
