### ISSUE TITLE
E119: Not enough arguments for function in Neovim

### ISSUE THREAD

**Issue by markwu** [ludovicchabant/vim-gutentags#163]
I just upgrade to master HEAD, it works well under vim8, but not in Neovim, it just shows `E119: Not enough arguments for function gutentags#default_io_cb` , here comes the screenshots.

![2018-04-01 10 31 12](https://user-images.githubusercontent.com/196861/38174216-93b7ac1e-35fc-11e8-98cf-2fa64b9f550b.png)

**Comment by markwu** [comment]
My Neovim version is 0.2.3-dev with `HEAD-c8fd7ce_1`. 
Macvim version is `8.0.1655`.

**Comment by danilo-augusto** [comment]
Same here. Latest `:PlugUpdate` broke it 😕

**Comment by markwu** [comment]
It fixed by this pr https://github.com/ludovicchabant/vim-gutentags/pull/162, not merged yet.

**Comment by danilo-augusto** [comment]
Thanks, @markwu

**Comment by ludovicchabant** [comment]
woops sorry about that! merged now, thanks.
