### ISSUE TITLE
cscope on windows doesn't work

### ISSUE THREAD

**Issue by skywind3000** [ludovicchabant/vim-gutentags#173]
I started to use gutentags when I saw your post in reddit (/r/vim). Now I use it everyday.

but just now, I am trying to get gutentags to manage my cscope files, I find it just can't work on windows.

after a short investigation, I found a issue:

https://github.com/ludovicchabant/vim-gutentags/blob/327bd979dd480a42b6edf3205136ac08cf349e8e/plat/win32/update_scopedb.cmd#L61-L72

line 67:

```Batch
%FILE_LIST_CMD% | for /F "usebackq delims=" %%F in (`findstr "."`) do @echo %PROJECT_ROOT%\%%F > %DB_FILE%.files
```

When variable `%FILE_LIST_CMD%` is empty (it is always empty in gutentags), this line becoms:

```Batch
 | for /F "usebackq delims=" %%F in (`findstr "."`) do @echo %PROJECT_ROOT%\%%F > %DB_FILE%.files
```

and the whole `if` statement from line 61 to 72 will no be executed because cmd.exe presume it as a syntax error (invalid bar `|` sign). and the update_scopedb.cmd will exit immediately. and cscope.exe will never be called.

I am using windows 10, I don't know whether cmd.exe in win7/xp will do the same syntax checking before executing the if statement. If it does, the whole `update_scopedb.cmd` is broken.

I have changed it to:

```batch
if NOT ["%FILE_LIST_CMD%"]==[""] (
    call %FILE_LIST_CMD% > %DB_FILE%.files
    set CSCOPE_ARGS=%CSCOPE_ARGS% -i %TAGS_FILE%.files
) ELSE (
    set CSCOPE_ARGS=%CSCOPE_ARGS% -R
)
```

and it works perfect, please consider to update `update_scopedb.cmd`.

**Comment by skywind3000** [comment]
I have made a PR for this, please review:

https://github.com/ludovicchabant/vim-gutentags/pull/174

**Comment by ludovicchabant** [comment]
Merged @yous' PR, hopefully this works.
