### ISSUE TITLE
How To Generate Ctags Include Python site-packages

### ISSUE THREAD

**Issue by twocucao** [ludovicchabant/vim-gutentags#179]
I need to browse my codebase with django app and django source code

How can i generate ctags with vim-gutentags with this?

```
ctags -R --fields=+l --languages=python --python-kinds=-iv -f ./.tags $(python -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))")
```

Thx

**Comment by twocucao** [comment]
No , for now I just generate ctags manually for browsing code

**Comment by twocucao** [comment]
@panosl 

You can generate pylibs.tags and put it into .vim/tags/ , then you can set tags+=/.vim/tags/pylibs.tags

Or 

You can use **autocmd** to setlocal tags+=~/.vim/tags/pylibs.tags when you detect python filetype

ref: https://github.com/skywind3000/gutentags_plus/issues/1

**Comment by panosl** [comment]
@twocucao there should be a way to automate it with .gutctags project file, so ti keeps things up-to-date when you install new packages/modules into your virtualenv.

**Comment by twocucao** [comment]
I agree with you, but it will take too much things into consideration? 

Maybe a gutentags_python.vim would be a better option?

Or 

Maybe gutentags can support bash command in . gutctags ?

**Comment by panosl** [comment]
the latter might be more appropriate IMO. You should keep the issue open so @ludovicchabant can have a look at it.

**Comment by ludovicchabant** [comment]
Hi!

It might be indeed better to have some `crontab` job or something that regenerates the `site-packages` tags on a regular basis, so you don't pay the (fairly heavy) cost of re-scanning your entire Python installation when you open _any_ Python project -- whether it's a big Django project or a small 1 file script.

However, Python development generally quickly ends up with virtual environments everywhere, with each project having its own... if you put those virtual environments inside the projects (like in a `venv` subfolder), Gutentags would scan that unless you tell it not too... if you use a virtual environment manager like `pipenv` or something, however, all those virtual environments are in a central place like `~/.venvs` and you're back to square one, except that now it _does_ make sense to index `site-packages` as part of the project. In which case yeah probably using a `.gutctags` file or somehow automating the process through `g:gutentags_file_list_command` would work... please report which one works :)

**Comment by panosl** [comment]
@ludovicchabant The best way would be to be able to specify

`let g:gutentags_file_list_command = 'python -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))"'`

but at a project level like a .gutctags file. Is there a way to do that?

**Comment by ludovicchabant** [comment]
There is _kind of_ a way to do that:

```
let g:gutentags_file_list_command = {'markers': 
    {'.pythontags': '/path/to/python_file_lister'}
}
```

Now if you write a `python_file_lister` that lists the current working directory's files plus the python site packages, you can enable that by putting a `.pythontags` file at the root of your project.

**Comment by twocucao** [comment]
@ludovicchabant 
@panosl 

That's great. 

Imo , In this python project , python-mode will be a better option. 

too many files may cause performance issues , thank you for your new feature !  I can use it for many other projects.

**Comment by panosl** [comment]
From @ludovicchabant suggestion I created a script that works for me, maybe others will find it useful as well:

https://gist.github.com/panosl/34ceba4228c111b9255ec6452d99cc48

**Comment by zippeurfou** [comment]
@ludovicchabant This would be great to add this as part of the doc with an example. I believe many people would benefit from it.

**Comment by tim-connolly** [comment]
Thanks for the suggestions, @ludovicchabant and @panosl . I had a bit of trouble getting things to work how I wanted them, so I am adding my script and .vimrc configuration here as a reference for anyone else looking to do this:-
https://gist.github.com/tim-connolly/2db6d7fcdd7dc1cc589f66e06532de24
