### ISSUE TITLE
Disabling Gutentags when resolving merge conflicts

### ISSUE THREAD

**Issue by snoblenet** [ludovicchabant/vim-gutentags#180]
When I rebase, I frequently edit the pre-image files that are created by git to resolve the merge conflicts.

When I quit the instance of Neovim started for this, Gutentags usually complains.

Is there a standard way to stop Gutentags launching in such circumstances in the first place?

If not, I guess I'll:

- set `g:gutentags_enabled` to `0`
- create an `autocmd` that checks `$(git rev-parse --git-dir)"/MERGE_HEAD`
- provisionally runs `g:gutentags_enabled` to `1`
- set it back to 0 before bufleave

**Comment by snoblenet** [comment]
`if &diff`

**Comment by ludovicchabant** [comment]
I'm thinking of adding a list of `filetype`s for Gutentags to check if it should enable or not (so, for example, it wouldn't activate for commit messages and stuff). Would the other/base files in a merge get a different `filetype`? I believe they do -- they get something like `diff`?

**Comment by snoblenet** [comment]
I'm afraid I've moved on. These days I just get Tmux to run `fswatch` in the root of the directory to create tags as required. But thanks.

**Comment by ludovicchabant** [comment]
Cool, enjoy your new toys :)

**Comment by magikid** [comment]
I also hit this same problem.  To get around it, I added this to my init.vim file:

```
" Add autogroup for tag generation
augroup tagAug
  autocmd!
  " If we're working in a git commit (or similar), disable tag file generation
  autocmd FileType git,gitcommit,gitrebase,gitsendemail :let g:gutentags_enabled=0
augroup end
```

**Comment by smemsh** [comment]
there is `g:gutentags_exclude_filetypes` now, FYI
