### ISSUE TITLE
APIs to get gtags database path ?

### ISSUE THREAD

**Issue by skywind3000** [ludovicchabant/vim-gutentags#181]
It's great that gutentags can generate gtags files for me in the background. But it could be better if gutentags can tell me where the gtags database files located. 

Gutentags can automatically add the gtags files via cscope interface by default. You may wonder that why I still need to know the database path. If I am editing two files from two different projects (very common), searching a symbol will get the results from both projects, because gutentags has already added two databases by gtags-cscope.

I don't need results from both projects, what I need is if I query words from file1, I should get the result from project1. and if I query words from file2, I should get the result from project2.

So, it is unwise to use the default behavior and I set `g:gutentags_auto_add_gtags_cscope` to `0` in my vimrc. Now, I write a vimscript command `GscopeFind` as a replacement of `:cs find`, but before actually calling `:cs find` it will check:

1. If the gtags database of current project has already been added, execute `:cs find` directly.
2. otherwise, disconnected all the other cscope connections and add a new connection of current project, then execute `:cs find`.

This `GscopeFind` command can guarantee the query result is right from the current project's gtags database. and gtags-cscope connections of previous project will be disconnected at the right moment. If you query result from the same project, gtags-cscope connection could be reused.

This script ([gutentags_plus.vim](https://github.com/skywind3000/vim/blob/master/plugin/gutentags_plus.vim)) works very well and will do exactly what I want. With a bit of hack, gutentags doesn't provide any apis to get the gtags database path, there is a buffer variable `b:gutentags_files` which contains the information of database paths and I am using it right now.

But I am still here and open this issue for new APIs because `b:gutentags_files` is undocumented in the help, which means it could be changed in the future, and I am afraid that my little script will break one day after updating gutentags.

Is it possible to provide apis for path information just like `gutentags#statusline()`, or document the `b:gutentags_files` variable in the help? If so, using gtags will be as convenient as using ctags in vim with my `GscopeFind` command.

**Comment by skywind3000** [comment]
update: I am using cache dir,

```VimL
let g:gutentags_cache_dir = expand('~/.cache/tags')
```

**Comment by skywind3000** [comment]
I have created the new plugin: [gutentags_plus](https://github.com/skywind3000/gutentags_plus). 

Would you please make a link to it in the README.md ?? Gutentags users may interest.

**Comment by ludovicchabant** [comment]
Cool, thanks for the new plugin! I actually personally use different Vim instances for different projects, so I don't actually run into this problem, but it does make sense if the projects are closely related enough that you want both in the same Vim instance... I added some links to your plugin! Cheers.
