### ISSUE TITLE
Error when open project

### ISSUE THREAD

**Issue by huyvohcmc** [ludovicchabant/vim-gutentags#182]
Recently I put this line into my vimrc: `let g:gutentags_trace = 1` and have found an error while opening any file in a project:
<img width="1388" alt="screen shot 2018-05-19 at 11 26 27 pm" src="https://user-images.githubusercontent.com/17645203/40270700-1a16977c-5bbc-11e8-89f8-06ad28eac053.png">

**Comment by ludovicchabant** [comment]
Hi! Sorry about that. I believe it's fixed with df66513fe95cc6a4aa99ca5cd1f429fc86cc4750.
