### ISSUE TITLE
Can I manually generate tags files? 

### ISSUE THREAD

**Issue by fcying** [ludovicchabant/vim-gutentags#187]
some git directories not need  tags
when I set follow setting,  and run `GutentagsUpdate` in work dir, it not auto generate tags, but also not auto update tags  after file write
```
    let g:gutentags_generate_on_missing = 0
    let g:gutentags_generate_on_new = 0
    let g:gutentags_generate_on_write = 0
```

can I manually generate tags files, and if tags not missing, it can be auto update?

**Comment by ludovicchabant** [comment]
Hi!

I'm not sure I understand... you want Gutentags to _not_ do anything unless you manually run `GutentagsUpdate`, _but_ you _do_ want it to auto-generate when you save something?

In that case you might just need to change `g:gutentags_generate_on_write` to `1`, but that actually won't work the way you think.

FYI:

- `g:gutentags_generate_on_missing`: when opening a file in a project that has _no_ tags file, let Gutentags auto-generate that tags file.
- `g:gutentags_generate_on_new`: when opening a file in a project that hasn't been "seen" yet in this Vim session, let Gutentags re-generate the tags file.
- `g:gutentags_generate_on_write`: when saving a file, _incrementally update_ the tags file.

The key here is "incrementally update", _i.e._ it will just rescan the file you saved, and patch the existing tags file to include the results of that scan. It will _not_ regenerate the entire tags file from the entire codebase.

As a result, if you have all settings to `0` but `on_write` to `1`, it will try to incrementally update a tags file that is missing or outdated.

For what you want, you'd have to keep those settings to `0` like you did, but write your own `BufWritePost` auto-command to run `GutentagsUpdate` when you write a file... but that would be pretty inefficient when the project's codebase size gets past a certain size.

**Comment by fcying** [comment]
Thanks Reply.

**Comment by ludovicchabant** [comment]
Cool! Thanks.
