### ISSUE TITLE
Keeping the tag file out of the way

### ISSUE THREAD

**Issue by ArsenArsen** [ludovicchabant/vim-gutentags#194]
Hello!
Let me preface this by thank you for your great work, I really do appreciate how well gutentags works. But I'd like to suggest possibly moving the generated tagfile into the SCM directory, so that SCM's doesn't pick it up (this is especially annoying with git, especially for us people who just do `git stage .` and call it a day). While I am not sure is Vim capable of reading that file later it would certainly reduce the clunkyness factor that might come with a tag file.

**Comment by ludovicchabant** [comment]
Hi! Thanks!

You have 2 choices to keep the tag file out of the way of the SCM:

1. Using Gutentags, use the `g:gutentags_cache_dir` setting (see [the help description](https://github.com/ludovicchabant/vim-gutentags/blob/master/doc/gutentags.txt#L411)), which makes all tags files generated in the given cache directory. It works fairly well, but Gutentags has to do a few workarounds to make it work.

2. A lot simpler (and how you're supposed to handle it in theory) is to just setup a global "ignore" rule for the `tags` file in your SCM.

  If you're using Git, you would use a [global exclude file][1]:

  ```
  git config --global core.excludesfile '~/.cvsignore'
  echo tags >> ~/.cvsignore
  ```

  If you're using Mercurial, you would add a [global ignore file][2] to your `~/.hgrc`:

  ```
  [ui]
  ignore = ~/hgignore.ini
  ```

  There are most definitely other ways for other SCMs.

[1]: https://help.github.com/articles/ignoring-files/#create-a-global-gitignore
[2]: https://www.mercurial-scm.org/doc/hgrc.5.html#ui

**Comment by ArsenArsen** [comment]
Well I did not know about global exclude files, that certainly comes in handy! Thanks. I'll also incorporate no. 1.
