### ISSUE TITLE
Extreme lag / slow / freezes when typing or backspacing

### ISSUE THREAD

**Issue by kkoomen** [ludovicchabant/vim-gutentags#199]
I noticed that Gutentags is the one that makes my vim very slow or even "freeze" when backspacing words or even typing words. If you look at the video below (wait for 5 seconds atleast) and you'll see when I am holding down backspace for roughly 1 second, you can see it lags a lot. You can also see I am disabling Gutentags and then the problem is gone immediately. I even have the semantic triggers disabled for PHP as a tesst as you saw in the video and the problem is still occuring then.

What could be the issue here? As you can see, the file is not bing. It contains < 100 lines, but this is a Drupal project and the actual tags file contains 85.000+ entries. Is this the problem? I have no idea. 

This is not a thing in smaller projects I believe, but this is really annoying it makes my vim "freeze".  Any idea what this could be?

![gutentags-lag-experience-kapture](https://user-images.githubusercontent.com/10693490/43824149-7eb99b38-9af1-11e8-99ba-ca5b7a43517a.gif)

Thanks in advance.

**Comment by ludovicchabant** [comment]
@kkoomen did you close the issue because you figured it out? My guess is maybe that when you disable Gutentags, it doesn't set the `tags` file anymore so you don't get any autocompletion anymore, and that's what's actually slowing it down?

**Comment by MrMino** [comment]
I happen to have the same issue when browsing trhough [CPython](https://github.com/python/cpython) codebase.
