### ISSUE TITLE
:verbose GutentagsUpdate instead of g:gutentags_trace

### ISSUE THREAD

**Issue by mgedmin** [ludovicchabant/vim-gutentags#202]
Have you considered supporting `:verbose GutentagsUpdate` instead of, or in addition to, `g:gutentags_trace`?   It would be easier to enable it just for a single command execution.

Implementation-wise all you need to do is check `&verbose > 0` in vimscript instead of/in addition to checking `g:gutentags_trace`.

**Comment by ludovicchabant** [comment]
Good idea! Done in 124dc58d68a10eb2c37639e75e1380f0a1b5c9b5. Thanks!
