### ISSUE TITLE
How to get gutentags_file_list_command to work

### ISSUE THREAD

**Issue by trevordmiller** [ludovicchabant/vim-gutentags#208]
First, thanks so much for a wonderful plugin! It is very useful and I really appreciate your work on it!

I'm trying to figure out a better system for ignoring directories/files from ctags. Up to this point, I've been using Universal Ctags with a `.ctags.d/config.ctags` config that looks like:

```
# GENERAL
--exclude=.git
--exclude=.DS_Store

# JAVASCRIPT
--exclude=node_modules
--exclude=package-lock.json
...
```

However, many of the projects I work on have specific compiled output that I'd like to ignore as well so this file keeps getting longer. I would like to instead rely on my `ag` (silver searcher) file list, since these are the source files I actually care about. After reading through a few other issues like https://github.com/ludovicchabant/vim-gutentags/issues/136, I've tried setting `let g:gutentags_file_list_command = 'ag -l'`, but this leads to Gutentags hanging with an empty `tags.files`.

I've tried this with multiple repos with the same result, so I don't think it is a problem specific to my project. I enabled `let g:gutentags_trace = 1` and get the following:

# Default setup

With a default setup, without Gutentags specific config, I get a `tags` output and everything works.

<img width="2179" alt="screen shot 2018-10-29 at 2 20 18 pm" src="https://user-images.githubusercontent.com/5497885/47679686-75048380-db8a-11e8-9053-22534b08f0fa.png">

# After adding `let g:gutentags_file_list_command = 'ag -l'`:

```
gutentags: Scanning buffer '/Users/trevordmiller/repos/dotfiles/index' for gutentags setup...
gutentags: No specific project type.
gutentags: Setting gutentags for buffer '/Users/trevordmiller/repos/dotfiles/index'
gutentags: Generating missing tags file: /Users/trevordmiller/repos/dotfiles/tags
gutentags: Running: ['/Users/trevordmiller/.vim/plugged/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', 'tags', '-p', '.', '-L', 'ag -l', '-l', 'tags.log']
gutentags: 'Locking tags file...'
```

It hangs indefinitely on `Locking tags file...`, never outputting a `ctags` file.

The output of `ag -l` is a small list of source files, as I would expect. So it seems there may be a problem with the Gutentags output of 

![image](https://user-images.githubusercontent.com/5497885/47679816-be54d300-db8a-11e8-8bbd-2beab0641277.png)

vs

![image](https://user-images.githubusercontent.com/5497885/47679829-c7de3b00-db8a-11e8-8ddb-278ee42abd0d.png)

once `let g:gutentags_file_list_command = '{command}'` is added?

**Comment by trevordmiller** [comment]
Related: https://github.com/universal-ctags/ctags/issues/218

**Comment by ludovicchabant** [comment]
Hi!
Have you tried running that `update_tags.sh` command line by hand to see if it outputs anything useful before hanging? You can also inspect the `tags.log` file that it left behind for any other clues.

**Comment by trevordmiller** [comment]
@ludovicchabant I updated to latest `vim-gutentags`. Once I add the two lines mentioned to my `.vimrc` and delete the project `tags` file, I am still getting the hanging output with a `tags.lock` with `36046` and an empty `tags.files` when I open the first buffer:

```
"~/repos/dotfiles/files/.vimrc" 86L, 1992C
gutentags: Scanning buffer '/Users/trevordmiller/repos/dotfiles/files/.vimrc' for gutentags setup...
gutentags: No specific project type.
gutentags: Setting gutentags for buffer '/Users/trevordmiller/repos/dotfiles/files/.vimrc'
gutentags: Generating missing tags file: /Users/trevordmiller/repos/dotfiles/tags
gutentags: Wildignore options file is up to date.
gutentags: Running: ['/Users/trevordmiller/.vim/plugged/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', 'tags', '-p', '.', '-L', 'ag -l', '-l', 'tags.log']
gutentags: [job output]: 'eval ag -l > "tags.files"'
```

If I run `/Users/trevordmiller/.vim/plugged/vim-gutentags/plat/unix/update_tags.sh -e ctags -t tags -p . -L 'ag -l' -l tags.log`, I get this output:

```
Locking tags file...
Running file list command
eval ag -l > "tags.files"
Running ctags on whole project
ctags -f "tags.temp"  -L tags.files
Replacing tags file
mv -f "tags.temp" "tags"
Unlocking tags file...
Done.
```

And the same "There is a tags file generated in the project root when I ran it manually like this, but the tags has files in it that are not in `ag -l`."

**Comment by trevordmiller** [comment]
I'll close this for now since it seems I am the only one who has ran into this.

**Comment by faisal-shah** [comment]
I have the identical problem. Running update_tags.sh works like a charm:

$ ~/.vim/plugged/vim-gutentags/plat/unix/update_tags.sh -e ctags -t tags -p . -L 'ag -l' -l tags.log
Locking tags file...
Running file list command
eval ag -l > "tags.files"
Running ctags on whole project
ctags -f "tags.temp"  -L "tags.files"
Replacing tags file
mv -f "tags.temp" "tags"
Unlocking tags file...
Done.


However, in Vim it doesn't work. Below is the :messages output:

gutentags: Scanning buffer '/home/dev/repos/project/main.c' for gutentags setup...
gutentags: No specific project type.
gutentags: Setting gutentags for buffer '/home/dev/repos/project/main.c'

gutentags: Generating missing tags file: /home/dev/repos/project/tags
gutentags: Wildignore options file is up to date.
gutentags: Running: ['/home/dev/.vim/plugged/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', 'tag
s', '-p', '.', '-L', 'ag -l', '-l', 'tags.log']
gutentags: In:      /home/dev/repos/project/speed
gutentags: [job stdout]: 'Locking tags file...'
gutentags: [job stdout]: 'Running file list command'
gutentags: [job stdout]: 'eval ag -l > "tags.files"'

... and then nothing.
