### ISSUE TITLE
Confused about how to enable tracing

### ISSUE THREAD

**Issue by somospocos** [ludovicchabant/vim-gutentags#210]
I'm running latest gutentags (revision 61fc8a9) with vim8 included patches: 1-1519

vim doesn't know about GutentagsToggleEnabled command - when I type :Gu then hit Tab, it only shows  :GutentagsUpdate

I see g:gutentags_trace mentioned in other issues and in the issue template, but a search for gutentags_trace in the doc file gutentags.txt gives no results

What am I doing wrong?

**Comment by ludovicchabant** [comment]
I just added a warning in the docs about those commands -- `GutentagsToggleTrace` and `GutentagsToggleEnabled` are only available if you enabled "advanced" commands (it's mentioned in the docs but it's not obvious, you need to read the paragraph above).

Anyway, to enable tracing, do `:let g:gutentags_trace = 1`.

If you have pulled the latest changes from today, you can alternatively do `:verbose GutentagsUpdate!` to run an update with tracing enabled.

**Comment by somospocos** [comment]
Thank you, I am getting traces now. Feel free to close the issue.
