### ISSUE TITLE
question: put tags file into project marker dir such as .git

### ISSUE THREAD

**Issue by Konfekt** [ludovicchabant/vim-gutentags#211]
Is there a way to tug the `tags` file into the project marker directory, such as `.git` for git repositories (as does the following shell script at https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html)?

```sh
#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
```

**Comment by ludovicchabant** [comment]
Hi! You can probably set `g:gutentags_ctags_tagfile` to `.git/tags` to achieve that.

**Comment by Konfekt** [comment]
Yeah, thanks. Good to know that `g:gutentags_ctags_tagfile` allows for a path relative to the project path. 

For other version control systems (`VCS`), it would be useful to have a variable `b:gutentags_vcs` that indicates the folder that the `VCS` stores its files in.

**Comment by Konfekt** [comment]
> What would that VCS setting do? Like, let you automatically put the tags file in .git/tags, .hg/tags, etc. depending on the current project's VCS? 

Exactly. Looks sensible and useful by any means, for different purposes, to have a variable indicating what kind of VCS is used. 

> Maybe... but do people do this often? I mean, what's wrong with either centralizing the tags file (using Gutentags' cache_dir) or leaving the files at the root but using a global Git/Mercurial/whatever ignore file that ignores tags files in all repos?

Not much wrong with it, after all, I personally do not find a `tags` file ignored by `.git/info/exclude`, put there by a template, much of a hassle. 

But this, tugging `tags` into `.git`, is how @tpope does it in https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html 
His approach would no longer clash with gutentag's then.

**Comment by filbranden** [comment]
+1.

Yes, I mostly use git, so setting `g:gutentags_ctags_tagfile` to `.git/ctags` is enough, but a more general option that works with other VCS's and automatically uses `<vcsdir>/ctags` (assuming `g:gutentags_ctags_tagfile` is unset/default) would be great.

**Comment by ludovicchabant** [comment]
I'll close this and leave the exercise of automatically setting `g:gutentags_ctags_tagfile` based on the VCS to the user or to another plugin.
