### ISSUE TITLE
Wildignore not respected with new "tmp file" feature

### ISSUE THREAD

**Issue by kristijanhusak** [ludovicchabant/vim-gutentags#212]
**Describe the bug**
Recently you added a feature where all exclude patterns are saved into temp file, and read when generating a tags file with `--exclude=@/tmp...`. For some reason this is not working for me. When i checkout a commit before this change, everything works fine. I'm using universal ctags, and it may be bug with them, but i want to make sure first.

**Steps to reproduce**
1. Get some javascript project, do `npm install` on it. I'm assuming it happens with anything else
2. add `set wildignore=node_modules` to your vimrc
3. Open up any js file from the project
4. Check tags file, has all node_modules stuff generated

**Share your setup**
- Linux mint 19, neovim V0.3.2-dev
- Universal ctags, --version print below
```
Universal Ctags 0.0.0(befcb888), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Nov 13 2018, 15:55:29
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath
```
- Are you using `g:gutentags_cache_dir`? - No

**Post the logs**
- I'll post only small part of it, because it's huge

```
gutentags: [job output]: ['Locking tags file...', 'Running ctags on whole project', 'ctags -f "tags.temp"  --options=/home/kristijan/.con
fig/nvim/pack/packager/start/vim-gutentags/res/ctags_recursive.options --exclude=@/tmp/nvim0kuvin/12 .', '']
LanguageClient project root: /home/kristijan/code/project/api
gutentags: [job output]: ['ctags: Warning: ']
gutentags: [job output]: ['ignoring null tag in node_modules/joi/lib/types/string/index.js(line: 20)']
gutentags: [job output]: ['', '']
gutentags: [job output]: ['ctags: Warning: ']
gutentags: [job output]: ['ignoring null tag in node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js(line: 768)']
gutentags: [job output]: ['', '']
gutentags: [job output]: ['ctags: Warning: ']
gutentags: [job output]: ['ignoring null tag in node_modules/slice-stream/node_modules/readable-stream/lib/_stream_readable.js(line: 855)
']

// A lot of more here

// End
gutentags: [job output]: ['ignoring null tag in node_modules/objectmodel/node_modules/debug/src/node.js(line: 238)']
gutentags: [job output]: ['', '']
gutentags: [job output]: ['ctags: Warning: ignoring null tag in node_modules/jest-jasmine2/build/jasmine/report_dispatcher.js(line: 45)', '']
gutentags: [job output]: ['ctags: Warning: ']
gutentags: [job output]: ['ignoring null tag in node_modules/whatwg-url/lib/URLSearchParams-impl.js(line: 115)']
gutentags: [job output]: ['', '']
gutentags: [job output]: ['ctags: Warning: ignoring null tag in node_modules/whatwg-url/lib/urlencoded.js(line: 2)', '']
gutentags: [job output]: ['ctags: Warning: ignoring null tag in node_modules/whatwg-url/lib/url-state-machine.js(line: 6)', '']
gutentags: [job output]: ['ctags: Warning: ignoring null tag in node_modules/whatwg-url/lib/URL-impl.js(line: 47)', '']
```

**Additional context**

I tried running the ctags command manually with the same temp file, and got the same results. I also removed all the exclude patterns except node_modules (I have more in my vimrc), and tried rerunning. Got same thing.
This leads me to believe that this is universal ctags issue, but please confirm if you can.

**Comment by ludovicchabant** [comment]
Ah yeah sorry about that! I pushed 93616e4c0ccfafe52ae329c7dd220d7b5c7d5f80 to fix this... I got mixed up between options files and exclude pattern files, because I just realized some of my `wildignore` patterns were _also_ in my custom `.ctagsrc` file! Aargh.
