### ISSUE TITLE
Support pycscope

### ISSUE THREAD

**Issue by ixil** [ludovicchabant/vim-gutentags#218]
It would be great if gutentags could support [pycscope](https://github.com/lonetwin/pycscope)  as a module.
`let g:gutentags_cscope_executable='pycscope'` results in `gutentags: gutentags: gtags-cscope job failed, returned: 122` when running `GutentagsUpdate`

**Comment by ixil** [comment]
@drozdowsky no I left it for the moment as I had other work to do. I may come back to it if I pick up the project I was working on before.

**Comment by ludovicchabant** [comment]
I'll close this and deal with the PR instead.
