### ISSUE TITLE
unexpected custom root finder behavior

### ISSUE THREAD

**Issue by damnskippy** [ludovicchabant/vim-gutentags#223]
When using `gutentags_project_root_finder` to find the root, there are times when the given file path is such that there isn't a proper root directory available, and generation of ctags is not desired.

However there seems to be no way to suppress the ctags generation in such cases.  Even `gutentags_exclude_project_root` option is not honored when using `gutentags_project_root_finder` I noticed.  If the `gutentags_project_root_finder` returns an empty string, gutentags proceeds to generate tags in the current working directory.  One could say that if the current working directory is desired then the root finder would've/should've returned `'.'`. 
If gutentags can treat empty string returned from the custom finder `gutentags_project_root_finder` as a way of saying "no root was found" and abort tag generation, that seems more desirable behavior.

This does it for me:
```
--- a/autoload/gutentags.vim
+++ b/autoload/gutentags.vim
@@ -272,6 +272,10 @@ function! gutentags#setup_gutentags() abort
         if !exists('b:gutentags_root')
             let b:gutentags_root = gutentags#get_project_root(l:buf_dir)
         endif
+        if !len(b:gutentags_root)
+            call gutentags#trace("no valid project root.. no gutentags support.")
+            return
+        endif
         if filereadable(b:gutentags_root . '/.notags')
             call gutentags#trace("'.notags' file found... no gutentags support.")
             return

```

**Comment by ludovicchabant** [comment]
Good point, thanks! Added with 4324f37d68bb642019eb71a43c6fc590ba065cc4.
