### ISSUE TITLE
tags generation successful but vim does not pick them up!

### ISSUE THREAD

**Issue by simlei** [ludovicchabant/vim-gutentags#227]
I configured gutentags as described in the docs. Up to a point, everything is working fine. That point is, to type `:tags` -- no tags are displayed.

But, the actual `tags` file is generated correctly. Gutentags trace shows
```
"rc/generalfuncs.vim" 719L, 24140C
gutentags: Scanning buffer 'rc/generalfuncs.vim' for gutentags setup...
gutentags: Setting project type to vim
gutentags: Setting gutentags for buffer 'rc/generalfuncs.vim'
```

and  the buffer in question correctly has its variables set:
```
: echo b:gutentags_files
: echo b:gutentags_root
{'ctags': '/home/simon/touchstone/modules/vim/vim-config/tags'}
/home/simon/touchstone/modules/vim/vim-config
```
Manual inspection of that `tags` file shows there are tags in it for that buffer. still, `:tags<CR>` yields only an empty list.

Am I missing something? is vim not supposed to pick up the tags then natively?

**Comment by matthsims** [comment]
Check out `:h :tags`. It does not display tags found, but the tags you have jumped to. Check `:h tag-highlight` for a quick mapping that generates a file with the tags in the file.

**Comment by ludovicchabant** [comment]
If you do `:echo tagfiles()`, what do you get? (it should print the list of `tags` files that Vim is currently taking into account... so typically it shows `['/path/to/tags']`).

The `g:gutentags_ctags_auto_set_tags` setting defines whether or not Gutentags should tell Vim about the generated `tags` file (so that it shows up in `:echo tagfiles()`). It defaults to `1` but maybe you have it turned off somehow?  Anyway, when it's on, it's supposed to add `b:gutentags_files['ctags']` to the Vim tags (by running `:execute('setlocal tags^='.b:gutentags_files['ctags'])`).

**Comment by nqiu** [comment]
> I configured gutentags as described in the docs. Up to a point, everything is working fine. That point is, to type `:tags` -- no tags are displayed.
> 
> But, the actual `tags` file is generated correctly. Gutentags trace shows
> 
> ```
> "rc/generalfuncs.vim" 719L, 24140C
> gutentags: Scanning buffer 'rc/generalfuncs.vim' for gutentags setup...
> gutentags: Setting project type to vim
> gutentags: Setting gutentags for buffer 'rc/generalfuncs.vim'
> ```
> 
> and the buffer in question correctly has its variables set:
> 
> ```
> : echo b:gutentags_files
> : echo b:gutentags_root
> {'ctags': '/home/simon/touchstone/modules/vim/vim-config/tags'}
> /home/simon/touchstone/modules/vim/vim-config
> ```
> 
> Manual inspection of that `tags` file shows there are tags in it for that buffer. still, `:tags<CR>` yields only an empty list.
> 
> Am I missing something? is vim not supposed to pick up the tags then natively?

Hey, I hit the same issue here. Have you gotten it solved?

**Comment by nqiu** [comment]
> If you do `:echo tagfiles()`, what do you get? (it should print the list of `tags` files that Vim is currently taking into account... so typically it shows `['/path/to/tags']`).
> 
> The `g:gutentags_ctags_auto_set_tags` setting defines whether or not Gutentags should tell Vim about the generated `tags` file (so that it shows up in `:echo tagfiles()`). It defaults to `1` but maybe you have it turned off somehow? Anyway, when it's on, it's supposed to add `b:gutentags_files['ctags']` to the Vim tags (by running `:execute('setlocal tags^='.b:gutentags_files['ctags'])`).

`:echo tagfiles()` shows an empty list.
`:echo g:gutentags_ctags_auto_set_tags`  shows the default value 1. 
After `:execute('setlocal tags^='.b:gutentags_files['ctags'])`, `:echo tagfiles()` shows the right tag files.
But vim didn't set tags files itself.

**Comment by nqiu** [comment]
> If you do `:echo tagfiles()`, what do you get? (it should print the list of `tags` files that Vim is currently taking into account... so typically it shows `['/path/to/tags']`).
> 
> The `g:gutentags_ctags_auto_set_tags` setting defines whether or not Gutentags should tell Vim about the generated `tags` file (so that it shows up in `:echo tagfiles()`). It defaults to `1` but maybe you have it turned off somehow? Anyway, when it's on, it's supposed to add `b:gutentags_files['ctags']` to the Vim tags (by running `:execute('setlocal tags^='.b:gutentags_files['ctags'])`).

I found an interesting thing. It seems that vim-gutentags does not support `https://github.com/EZLippi/Tinyhttpd` this project.

for my case, the project locates in `/home/nqiu/Workspace/Tinyhttpd`，the tags files can be auto generated at `/home/nqiu/.cache/tags/`，but when vim opens a source file, `:echo tagfiles()` shows an empty list

**Comment by nqiu** [comment]
I'm using spf13-vim，I found that after executing `:source ~/.vimrc`, `:echo tagfiles()` would return an empty list

**Comment by ludovicchabant** [comment]
Note that whatever Gutentags does affects the `&tags` variable. When you do `:echo tagfiles()`, Vim actually runs some logic by reading `&tags` and figuring out which of the list tag files are valid and exist and if none do then it shows you an empty list. So you should first do `:echo &tags` to see if Gutentags somehow added the wrong path. What does Vim report?

I just tried `Tinyhttpd` and it works fine at least on Mac and with the very latest Gutentags (as of today).

**Comment by tomdalling** [comment]
I'm having a similar problem. After working for a while, I try to jump to a tag and it says the tag does not exist. I look at `:echo &tags` and the Gutentags path is missing. If I quit and restart vim, `:echo &tags` includes the Gutentags path and everything works for a while, but the problem always comes back.

This happens very frequently, but I'm not exactly sure what is triggering it. I have a feeling it might be related to [Obsession](https://github.com/tpope/vim-obsession) or [Prosession](https://github.com/dhruvasagar/vim-prosession), but who knows.

**Comment by tomdalling** [comment]
I've reproduced my issue in #289

**Comment by ludovicchabant** [comment]
Cool, thanks, I'll close this one then.
