### ISSUE TITLE
$CTAGS_EXE need user define， in some condition

### ISSUE THREAD

**Issue by homway2016** [ludovicchabant/vim-gutentags#229]
in plat/unix 
if  /usr/bin/ctags need “/usr/bin”，how $CTAGS_EXE get “/usr/bin” as path

in my linux env， default  ctags is/@$@&/python/bin/ctags ，not GNU ctags

**Comment by ludovicchabant** [comment]
Check `:help gutentags_ctags_executable` -- the global setting `g:gutentags_ctags_executable` lets you specify a custom path to `ctags`.
