### ISSUE TITLE
There is an unmatched description in the help doc about the project root

### ISSUE THREAD

**Issue by steinsws** [ludovicchabant/vim-gutentags#238]
**Describe the bug**
In the help doc, the default markers are `['.git', '.hg', '.bzr', '_darcs', '_darcs', '_FOSSIL_', '.fslckout']`.
However, in the completion file gutentags.vim, the default markers are ` ['.git', '.hg', '.svn', '.bzr', '_darcs', '_FOSSIL_', '.fslckout']` where the '.svn' was not referred.

**Comment by ludovicchabant** [comment]
Thanks! Fixed with eecb136fae97e30d5f01e71f0d3b775c8b017385
