### ISSUE TITLE
Put tags file in ~/.vimrc

### ISSUE THREAD

**Issue by ChillerDragon** [ludovicchabant/vim-gutentags#272]
I keep commiting my ``tags`` file when I run ``git add .``. And people are annoyed that I put tags in the ``.gitignore`` of literally every project. So is there a way to put the ``tags`` file in the ``~/.vimrc`` directory?

**Comment by joaofcosta** [comment]
Hi @ChillerDragon , where's what I do to avoid this.

Create a global gitignore file, for example `~/.gitignore`, and add this:

```
# Ignore Exuberant Ctags file.
tags 
```

Afterwards just run this command to set your global gitignore file:

```
git config --global core.excludesfile ~/.gitignore
```

That should help you avoid commiting the tags file :)

**Comment by ChillerDragon** [comment]
@joaofcosta awesome thanks!
