### ISSUE TITLE
Presence of .gutctags leads to empty tags file

### ISSUE THREAD

**Issue by brtastic** [ludovicchabant/vim-gutentags#281]
I'm used to putting .gutctags files into my projects so that I avoid creating huge ctags files. My usual .gutctags file looks like this:
```
-L .gutctagsfiles
--exclude=node_modules
--exclude=vendor
```
This worked flawlessly for me for a long time, but latest commits made this behave incorrectly. To be exact, seems like once the .gutctags file is present (even if it's empty), the final tags file ends up being empty or almost-empty. Once the file is gone, a full tags file is generated.
I was able to narrow down the problem, and seems like the last commit that works as it used to work is this one: eb9e57f579d2ef747be25a7a4ec5add6fe5ca3d9
The commit that comes after this one causes the problem described above.

**Comment by ludovicchabant** [comment]
Which OS are you running?
Does the `.gutctagsfiles` file exist? Does it contain relative or absolute paths?

**Comment by brtastic** [comment]
I am mostly using Linux (openSUSE leap 15.2), but I'm also having this problem on FreeBSD 12.1.
I only put `.gutctagsfiles` there if it actually exists. Pretty sure it contains relative paths, but can't check right now. But even if this file wasn't there in `.gutctags` I still had the problem described above.

**Comment by brtastic** [comment]
I can now confirm that my `.gutctagsfiles` file contains relative paths (no leading slash)

**Comment by ludovicchabant** [comment]
Ah, I know, the reason for that is that when you specify a `.gutctags`, it replaces the default options file provided by Gutentags (which sets by default the `--recursive=yes` option). So you have to re-specify the recursive flag in your `.gutctags`. It's not super obvious, sorry about that... but I did want to make it possible for people to have full control over the options. Arguably I could control the default option with another flag but I was lazy...
