### ISSUE TITLE
E475: Invalid argument: Channel doesn't exist

### ISSUE THREAD

**Issue by Freed-Wu** [ludovicchabant/vim-gutentags#283]
**Describe the bug**
Probably conflict with other plugins...

**Steps to reproduce**
1. test.vim
```
set runtimepath=$VIMRUNTIME,~/.vim/repos/github.com/ludovicchabant/vim-gutentags,~/.vim/repos/github.com/Yggdroot/LeaderF
```
2. open a terminal, type
```
nvim -u ~/.config/nvim/test.vim Desktop/test.txt
```
3. insert some text, save it. or delete some text. save it. quit.
4. in the terminal, some text will appear
```
Error detected while processing DirChanged Autocommands for "*":
E475: Invalid argument: Channel doesn't exist
E475: Invalid argument: Channel doesn't exist
Error detected while processing function <SNR>29_nvim_job_exit_wrapper[1]..gutentags#ctags#on_job_exit[1]..gutentags#remove_job_by_data[2]..gutentags#remove_job:
line   22:
E171: Missing :endif
```
PS: the script 29 is gutentags
![image](https://user-images.githubusercontent.com/32936898/84889326-49ba0980-b0cb-11ea-8885-6dce0ce6ad5d.png)

**Share your setup**
OS: linux 5.4
vi: nvim 0.4.3

**Additional context**
I found if remove `$VIMRUNTIME` and `Yggdroot/LeaderF`, the error information will not appear. so i guess perhaps some plugins have conflict.

**Comment by niklaas** [comment]
Looks to me like #269 .

**Comment by ludovicchabant** [comment]
Can't repro with neovim 0.4.4 and the latest LeaderF... can you try again?

**Comment by Freed-Wu** [comment]
![image](https://user-images.githubusercontent.com/32936898/95305510-a62e7800-08b8-11eb-9ba5-839b1380bc9a.png)

this is my environment:

```{.vim}
" File: $XDG_CONFIG_HOME/nvim/test.vim
" OS: linux v5.4.13
" Vi: nvim v0.4.3
" Py: cpython v3.6.10
" Term: guake v3.7.0
set runtimepath=$VIMRUNTIME,~/.vim/repos/github.com/ludovicchabant/vim-gutentags,~/.vim/repos/github.com/Yggdroot/LeaderF
" vi -u $XDG_CONFIG_HOME/nvim/test.vim
```

**Comment by Freed-Wu** [comment]
in <https://github.com/Yggdroot/LeaderF/blob/master/plugin/leaderf.vim#L77>,
```{.vim}
autocmd BufWritePost * call leaderf#Gtags#updateGtags(expand('<afile>:p'), 1)
```

```{.vim}
function! leaderf#Gtags#updateGtags(filename, single_update)
exec g:Lf_py "<< EOF"
gtagsExplManager.updateGtags(lfDecode(vim.eval("a:filename")), True if int(vim.eval("a:single_update")) else False)
EOF
endfunction
```
looks like leaderf is in conflict with gutentags.

**Comment by Freed-Wu** [comment]
looks like it is same as #269

**Comment by elecalion** [comment]
> in https://github.com/Yggdroot/LeaderF/blob/master/plugin/leaderf.vim#L77,
> 
> ```
> autocmd BufWritePost * call leaderf#Gtags#updateGtags(expand('<afile>:p'), 1)
> ```
> 
> ```
> function! leaderf#Gtags#updateGtags(filename, single_update)
> exec g:Lf_py "<< EOF"
> gtagsExplManager.updateGtags(lfDecode(vim.eval("a:filename")), True if int(vim.eval("a:single_update")) else False)
> EOF
> endfunction
> ```
> 
> looks like leaderf is in conflict with gutentags.

looks like this line works for me
`let g:Lf_GtagsAutoUpdate = 0`
