### ISSUE TITLE
[Advice] change the default value of g:gutentags_exclude_project_root

### ISSUE THREAD

**Issue by Freed-Wu** [ludovicchabant/vim-gutentags#308]
``` txt
g:gutentags_exclude_project_root
                        Defaults to `['/usr/local']`, which is the folder where
                        Homebrew is known to create a Git directory by default
                        on MacOS.
```

According to <https://docs.brew.sh/FAQ#why-is-the-default-installation-prefix-opthomebrew-on-apple-silicon> and <https://docs.brew.sh/FAQ#why-is-the-default-installation-prefix-homelinuxbrewlinuxbrew-on-linux>

    Why is the default installation prefix /opt/homebrew on Apple Silicon?

    The prefix /opt/homebrew was chosen to allow installations in /opt/homebrew for
    Apple Silicon and /usr/local for Rosetta 2 to coexist and use bottles.

    Why is the default installation prefix /home/linuxbrew/.linuxbrew on Linux?
    ...

Perhaps the default value of `g:gutentags_exclude_project_root` should be `['/usr/local', '/opt/homebrew', '/home/linuxbrew/.linuxbrew']`?

**Comment by ludovicchabant** [comment]
Sounds good!  See b77b8fabcb0b052c32fe17efcc0d44f020975244
Thanks
