### ISSUE TITLE
cpu almost 100%

### ISSUE THREAD

**Issue by ltang666** [ludovicchabant/vim-gutentags#313]
![image](https://user-images.githubusercontent.com/3445470/142557384-71a95c0b-e504-439e-a6df-94d2675221e2.png)

/bin/sh /data/mm64/.vim/plugged/vim-gutentags/plat/unix/update_tags.sh -e ctags -t /data/mm64/.cache/tags/data-mm64-search-.tags -p /data/mm64/ -o /data/mm64/.vim/plugged/vim-gutentags/res/ctags_recursive.options -O --fields=+niazS -O --extra=+q -O --c++-kinds=+px -O --c-kinds=+px -O --output-format=e-ctags -x @/data/mm64/.cache/tags/_wildignore.options

code is very large.

OS : CentOS Linux release 7.2 (Final)
vim version： Vi IMproved 8.2 Included patches: 1-3588
ctags： Universal Ctags 5.9.0(p5.9.20211114.0)
gtags：gtags (Global) 6.6.7
using let g:gutentags_cache_dir = expand('~/.cache/tags') in vimrc

vimrc
```
Plug 'skywind3000/gutentags_plus'
" enable gtags module
let g:gutentags_modules = ['ctags', 'gtags_cscope']
" config project root markers.
let g:gutentags_project_root = ['.root']
" generate datebases in my cache directory, prevent gtags files polluting my project
let g:gutentags_cache_dir = expand('~/.cache/tags')
" change focus to quickfix window after search (optional).
let g:gutentags_plus_switch = 1 
let g:gutentags_ctags_tagfile = '.tags'
let g:gutentags_modules = []
if executable('ctags')
    let g:gutentags_modules += ['ctags']
endif
if executable('gtags-cscope') && executable('gtags')
    let g:gutentags_modules += ['gtags_cscope']
endif
let g:gutentags_ctags_extra_args = ['--fields=+niazS', '--extra=+q']
let g:gutentags_ctags_extra_args += ['--c++-kinds=+px']
let g:gutentags_ctags_extra_args += ['--c-kinds=+px']
let g:gutentags_ctags_extra_args += ['--output-format=e-ctags']
let g:gutentags_auto_add_gtags_cscope = 0 
```

**Comment by philpem** [comment]
I've seen this with large projects - in my case a Buildroot project directory. Gutentags tried to index the whole thing, ran the CPU up to 100% and filled up `$HOME`.
I think the correct fix is to create a `.notags` file to stop Gutentags trying to index the root Git project, but I couldn't get this to work.
