### ISSUE TITLE
gutentags_generate_on_missing is not working as intended

### ISSUE THREAD

**Issue by egidijusz** [ludovicchabant/vim-gutentags#32]
`let g:gutentags_generate_on_missing = 0` does not disable automatic tags generation.

```
let g:gutentags_generate_on_missing = 0
let g:gutentags_generate_on_new = 0
```
did the trick.

I suppose this is the offender https://github.com/ludovicchabant/vim-gutentags/blob/master/autoload/gutentags.vim#L140 .
What does `gutentags_generate_on_new` do? ( #26 ) .

**Comment by ludovicchabant** [comment]
I added some documentation on it with 8ae5b65ebec50dd9e5eec1e5a2a407512dce244d.
It basically (re)generates the tag file when you open the first file in a project -- regardless of whether the tag file is already there or not. This is useful if you typically (re)open Vim after having sync'ed/pulled (so the tag file is updated with the new source code right away).
Sorry for the trouble!

**Comment by sswam** [comment]
I don't want gutentags ever to automatically generate a tags file if it is not already there.

The suggested configuration is not working for me:

```
let g:gutentags_generate_on_missing = 0
let g:gutentags_generate_on_new = 0
```

How may I prevent it generating a new file?
