### ISSUE TITLE
Does it support different ctags file chosen dynamically?

### ISSUE THREAD

**Issue by marcelolima** [ludovicchabant/vim-gutentags#328]
In my setup I'm already using gutentags to automatically create the tags for the repository I'm working on (python), and I have another shortcut for generating the tags just for the libraries (not done automatically since it takes time and would pollute the main app ctags file). Right now I'm trying to set up some new shortcut that would allow me to navigate to the definition using the libraries ctags file instead of the one that was initially passed to `g:gutentags_ctags_tagfile`, but can't find a good way. Has anyone done something similar?  

Eg:
```
g] -> use `gutentags_ctags_tagfile` normally
<F12> -> use the lib tagfile 
```

**Comment by wow-yes** [comment]
As what I understand, you want to create different tagfiles for different file-types. 

So, for example, we have `cpp` and `py` files in a repos.  How to create two tags for `cpp` and `py`  respectively？Here is my solution.

```vim

```

**Comment by ludovicchabant** [comment]
That's a nice trick @wow-yes thanks.

I think @marcelolima was maybe asking about switching the tagfile used for _looking up a symbol_? In that case, I think that temporarily setting the `tags` variable would work (see `:help 'tags'`), but frankly vim does a good job of handling multiple tag files anyway, so setting that variable to both tag files (separated by a space or comma) would let vim search both when typing `g]`. Usually gutentags sets that variable automatically but that could mess-up your setup in this case, so you can disable that with `g:gutentags_ctags_auto_set_tags`.
