### ISSUE TITLE
use gtags failed

### ISSUE THREAD

**Issue by guocf20** [ludovicchabant/vim-gutentags#332]
**Describe the bug**
Describe what the bug is about, and what you expected. Don't forget to format things nicely with Markdown. If applicable, post screenshots.

**Steps to reproduce**
1. Do this '...'
2. Do that '...'
3. Etc.
ls -lhtr /root/.vim/plugged/vim-gutentags/plat/unix/
total 20K
-rw-r--r-- 1 root root  751 Jul 29 22:16 update_gtags.sh

**Share your setup**

**Post the logs**
gutentags: Scanning buffer 'src/main.c' for gutentags setup...
gutentags: No specific project type.
gutentags: Setting gutentags for buffer 'src/main.c'
gutentags: Generating tags file: /root/.cache/tags/mnt-d-source-vim_ide-vim/GTAGS
gutentags: Running: ['/root/.vim/plugged/vim-gutentags/plat/unix/update_gtags.sh', '-e', 'gtags', '--incremental', '/root/.cache/tags/mnt-d-source-vim_ide-vim']
gutentags: In:      /mnt/d/source/vim_ide/vim
gutentags:
gutentags: [job stderr]: 'executing job failed: Permission denied'
gutentags: Finished gtags_cscope job.
gutentags: gtags-cscope job failed, returned: 122

**Additional context**

chmod 755 /root/.vim/plugged/vim-gutentags/plat/unix/update_gtags.sh
update this files permission 755

may update_pyscopedb.sh have the same problem

**Comment by wow-yes** [comment]
All the `*.sh` files in plat/unix show be executable. 
```bash
chmod +x /root/.vim/plugged/vim-gutentags/plat/unix/*.sh
```

Maybe you should search before opening a new issue.

**Comment by ludovicchabant** [comment]
Yep, fixed with 865d17a63b70690beee855e72abd38db278c1839. Sorry for the delays.
