### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by greghensley** [ludovicchabant/vim-gutentags#40]
After looking around the code, your blog (http://ludovic.chabant.com/), and project site (http://bolt80.com/gutentags/), I have not been able to determine the license under which you have released the source for Gutentags.  Please provide a "LICENSE" or "CONTRIB" file specifying the license and (if applicable) any additional licensing rules which apply to contributions.

**Comment by ludovicchabant** [comment]
Indeed, good point. Fixed with 83d8c7bf72184155e8c30000f0c0c1b60eb2faa4. I'm licensing this with the MIT license to keep it simple :)
