### ISSUE TITLE
Does not handle paths with spaces on Windows

### ISSUE THREAD

**Issue by johatfie** [ludovicchabant/vim-gutentags#42]
I wish I could quit using Windows altogether, but I don't see that happening any time soon.  Whoever it was at Microsoft that thought allowing a space or spaces in a path was a good idea, was an idiot.

Anyhow, this doesn't work at all for paths with spaces in them.  I've forked this and started working on a fix, but it's not complete yet.  I've got as far as getting update_tags.cmd to run fine from the command line, but it doesn't work when called from within Vim.  I'll try to get my work in progress posted on GitHub tomorrow, but the easiest way to handle spaces is to quote all parameters before they go to the .cmd file.  That means not stripping the quotes from the args in update_tags.cmd and not quoting the variables later after parsing the args.

Also, I could find no way to call "start /b "d:\program files\rest_of_path\update_tags.cmd" without it generating a "d:\program is not a command" error.  I tried everything I could think of to escape the spaces without any success.  What did seem to work was 'start /b /d "d:\program files\rest_of_path" update_tags.cmd' which is specifying the starting directory separately.  It didn't require much in the way of changes, but it still didn't work when vim-gutentags called it in Vim.

Thanks.
Jon Hatfield

**Comment by johatfie** [comment]
Fixed!  It turned out to be much simpler than I thought.  The "!start /b"  needs to be followed by "cmd /c" and everything after that is enclosed in a set of double quotes.

**Comment by ludovicchabant** [comment]
I'll close this since the pull request is in progress for this.
