### ISSUE TITLE
Selectively disable tag regeneration for some file types?

### ISSUE THREAD

**Issue by vadz** [ludovicchabant/vim-gutentags#44]
This is perhaps more of a question than an issue, but I just can't find any way to disable tags regeneration when opening Vim to edit a git commit message. As I typically commit soon after making some changes (in an existing long-running Vim instance), this almost invariably results in an annoying (especially because it's too long and so has to be dismissed) message from gutentags about the tag file being already updated when it tries to update it in the new Vim instance too.

I tried putting `let g:gutentags_enabled=0` in `~/vim/ftplugin/gitcommit.vim` but this doesn't help as it's already too late by then. Is there some other way to configure the plugin to never generate tags when editing `COMMIT_EDITMSG`?

Or, alternatively, maybe it should detect that the generation is already in progress and silently do nothing then?

**Comment by ludovicchabant** [comment]
The message should be gone now with 02a9f0799ab972c4b73b588ce726212e704e2654 (it will only show up if the tag generation is done manually, like with `:GutentagsUpdate`). So maybe that actually fixes your problem?

Generally speaking I think it would be a good idea to have some way to tell Gutentags to not get up and running for some files, but I don't know yet what would be the best way to do that.... it seems to me there are different ways to go about it but I don't know which one is preferable.

**Comment by vadz** [comment]
Thanks, I hadn't noticed this change (I have some local modifications, so I don't update my copy often), it does look like it should fix the symptom of the problem.

I still agree with you that it would be better to avoid even trying to do it in the first place. Maybe have an option of filetypes editing which _should_ result in tag file (re)generation?

**Comment by ludovicchabant** [comment]
Well I just pushed that change yesterday so you wouldn't have seen it :)
