### ISSUE TITLE
Ambiguous output redirect for csh/tcsh

### ISSUE THREAD

**Issue by verbitan** [ludovicchabant/vim-gutentags#48]
My default shell is tcsh and this is causing issues when using gutentags, raising the following error when opening Vim or manually running GutentagsUpdate - `Ambiguous output redirect.`

This is due to using the `2>&1` redirect within `autoload/gutentags/ctags.vim`

**Comment by ludovicchabant** [comment]
I'm not familiar with the subtle differences between various shells... do you know what would be the correct redirect to use?

**Comment by Coacher** [comment]
Hello.

You should use `>&`. It is supported by both [bash](https://www.gnu.org/software/bash/manual/bashref.html#Redirecting-Standard-Output-and-Standard-Error) and [tcsh](http://www.tcsh.org/tcsh.html/Input_output.html) and `source >& target` is semantically equivalent to `source > target 2>&1` construction from bash.

**Comment by Coacher** [comment]
See also http://hyperpolyglot.org/unix-shells#redirection

**Comment by Coacher** [comment]
For the best portability, tcsh should be treated separately though.

**Comment by Coacher** [comment]
As described [here](http://www.tcsh.org/tcsh.html/Builtin_commands.html) tcsh also doesn't have `trap`, `read`, and `getopts`. See also [this](https://www.freebsd.org/cgi/man.cgi?query=trap&apropos=0&sektion=0&manpath=FreeBSD+10.2-RELEASE&arch=default&format=html). Is it worth the effort to support tcsh even?
