### ISSUE TITLE
let g:gutentags_enabled = 0 not respected

### ISSUE THREAD

**Issue by Konfekt** [ludovicchabant/vim-gutentags#52]
If `.vimrc` contains `let g:gutentags_enabled = 0` then saving a file in a git repo still makes ctags recreate the `tags` file.

**Comment by ludovicchabant** [comment]
That's weird, [this code here](https://github.com/ludovicchabant/vim-gutentags/blob/master/autoload/gutentags.vim#L212) specifically checks for it before regenerating the tags.

I tried repro'ing and it works as expected on my machine.

**Comment by Konfekt** [comment]
Well `echo g:gutentags_enabled` gives `0` and the process list shows `update_tags` working as soon as a file in a git repo is opened in vim.

**Comment by ludovicchabant** [comment]
Oh right, it does test it when saving the file, but not when opening it. Fixed with bc37714e57597b8fa8802b07e931eb668785e1c6, thanks.
