### ISSUE TITLE
Bundler Support

### ISSUE THREAD

**Issue by robhurring** [ludovicchabant/vim-gutentags#53]
Just curious if there was a way to handle gem dependency tags in ruby? I'm coming from https://github.com/szw/vim-tags which detects the Gemfile and includes the `bundle show --paths` automatically, and don't see a way to do that with gutentags. Is there a way to set that up natively that I'm missing, or would this be more of a feature/pull-request?

Related: https://github.com/ludovicchabant/vim-gutentags/issues/50

**Comment by ludovicchabant** [comment]
I think this would have to be some kind of additional mechanism that allows custom additional paths, since apparently you need to run a specific command to get the list of paths (and you probably want to have that cached until the Gemfile changes). So yeah, new feature.

**Comment by robhurring** [comment]
That makes sense. The tricky bit would be when to run it as re-tagging the entire gemset on write would really slow things down.

For anyone else curious about working around this - I'm using [gem ripper-tags](https://github.com/lzap/gem-ripper-tags) which automatically generates the gem's tags, and [vim-bundler](https://github.com/tpope/vim-bundler) to add the Gemfile's paths to vim's `path`.  It is working really well.

**Comment by ludovicchabant** [comment]
Cool, good to know, thanks.

**Comment by ludovicchabant** [comment]
I'll close that since I probably won't have time to write a feature I wouldn't use. Anybody's free to submit a patch with it though!
