### ISSUE TITLE
disable for all repos by default

### ISSUE THREAD

**Issue by goweol** [ludovicchabant/vim-gutentags#54]
I have so many git repositories including HOME directory.
I hope it supports some option which is enable only for some repos, but disabled all other repos  (inverse of .notags?).
For example,
<blockquote>
let g:gutentags_use_global_enable_dotfile = '.gutentags-enable'
</blockquote>
If user set such a variable, only enabled for a repo which contains such file.

Or only enable if 'tags' file already exists.   Maybe 'gutentags_only_update_mode'-like option?

**Comment by ludovicchabant** [comment]
Why do you want Gutentags to generate tags only for a few repos? Is it because most of the repos are too big, or don't contain code, or something?

**Comment by goweol** [comment]
I don't need to use tag for many GIT repo.
It is best to me, if gutentags is only enabled if 'tags' (or some given
filename) file is found.  Then, If I want to use tag, I will generate
basic tags file. Then, gutentags will automatically updated it if I do
some work.

**Comment by ludovicchabant** [comment]
Can you try this quick patch?

```diff
diff --git a/autoload/gutentags.vim b/autoload/gutentags.vim
--- a/autoload/gutentags.vim
+++ b/autoload/gutentags.vim
@@ -107,6 +107,12 @@
         return
     endif

+    " Let the user specify custom ways to disable Gutentags.
+    if g:gutentags_enabled_user_func != '' &&
+                \!call(g:gutentags_enabled_user_func, expand('%:p'))
+        return
+    endif
+
     " Try and find what tags file we should manage.
     call gutentags#trace("Scanning buffer '" . bufname('%') . "' for gutentags setup...")
     try
diff --git a/plugin/gutentags.vim b/plugin/gutentags.vim
--- a/plugin/gutentags.vim
+++ b/plugin/gutentags.vim
@@ -41,6 +41,10 @@
     let g:gutentags_enabled = 1
 endif

+if !exists('g:gutentags_enabled_user_func')
+    let g:gutentags_enabled_user_func = ''
+endif
+
 if !exists('g:gutentags_modules')
     let g:gutentags_modules = ['ctags']
 endif
```

It lets you specify the name of a function in `g:gutentags_enabled_user_func`. This function will get called with the path to each new buffer, and if it returns 0 (or some other false value), Gutentags will be disable for that buffer. You could make that function compare the given path to a list of white-listed repos, or check for the existence of a `tags` file, or something.

**Comment by goweol** [comment]
I tried with a simple func:
<blockquote>
    func! GutenTagsGenCheck(file)<br>
      "call gutentags#trace(gutentags#get_project_root(a:file))<br>
      return 0<br>
    endfunc<br>
    let g:gutentags_enabled_user_func = 'GutenTagsGenCheck'
</blockquote>

And I've got an error:
<blockquote>
Error detected while processing function gutentags#setup_gutentags:<br>
line   14:<br>
E714: List required
</blockquote>

Thanks

**Comment by ludovicchabant** [comment]
Woops sorry, typo in the code calling your custom function. Put square brackets around the second parameter:

```
      \!call(g:gutentags_enabled_user_func, [expand('%:p')])
```

**Comment by goweol** [comment]
Now it worked fine as I expected.
<pre>
    func! MyGutentagsFunc(file)
      let tag_file = gutentags#get_project_root(a:file).'/tags'
      return filereadable(tag_file)
    endfunc
    let g:gutentags_enabled_user_func = 'MyGutentagsFunc'
</pre>

Thanks!

**Comment by goweol** [comment]
With old MyGutentagsFunc(), I saw an error message when I run 'vim' without filename.
<pre>
Error detected while processing function gutentags#setup_gutentags[14]..MyGutent
agsFunc[1]..gutentags#get_project_root[17]..gutentags#throw:
line    2:
E605: Exception not caught: gutentags: Can't figure out what tag file to use for
: 
</pre>

So that, I changed it like below.  Does it correct? Is there any other way?
<pre>
    func! MyGutentagsFunc(file)
      try
        let tag_file = gutentags#get_project_root(a:file).'/tags'
        return filereadable(tag_file)
      catch
        return 0
      endtry
    endfunc
</pre>

**Comment by ludovicchabant** [comment]
Ok I submitted the patch (see a844f0871e0224134d0c03bff1686d7e52d28e55).

A `try...catch` is probably a good idea, but when I run `vim` with no arguments the callback doesn't get called for me (because the default buffer is not a writable file). Maybe you have Vim setup to open something by default?
