### ISSUE TITLE
Generate tags with --fields=+l for YouCompleteMe support

### ISSUE THREAD

**Issue by daniel2887** [ludovicchabant/vim-gutentags#55]
YouCompleteMe can autocomplete from tags files, but the tags file needs to be generated with --fields=+l.

The following patch seems to work ok (in my limited testing!). Have you considered adding this flag?
```
diff --git a/plat/unix/update_tags.sh b/plat/unix/update_tags.sh
index a4366e4..18ddbfd 100755
--- a/plat/unix/update_tags.sh
+++ b/plat/unix/update_tags.sh
@@ -80,7 +80,7 @@ fi
 
 echo "Running ctags"
 echo "$CTAGS_EXE -f \"$TAGS_FILE.temp\" $CTAGS_ARGS \"$PROJECT_ROOT\""
-$CTAGS_EXE -f "$TAGS_FILE.temp" $CTAGS_ARGS "$PROJECT_ROOT"
+$CTAGS_EXE -f "$TAGS_FILE.temp" $CTAGS_ARGS "$PROJECT_ROOT" --fields=+l
 
 echo "Replacing tags file"
 echo "mv -f \"$TAGS_FILE.temp\" \"$TAGS_FILE\""
```

**Comment by daniel2887** [comment]
I suppose that this is a better patch:
```
diff --git a/res/ctags.options b/res/ctags.options
index e13de4a..42ec57e 100644
--- a/res/ctags.options
+++ b/res/ctags.options
@@ -1,2 +1,4 @@
 --recurse=yes
+--fields=+l
```

**Comment by ludovicchabant** [comment]
You can just create a `.ctags` file in your home directory, and add `--fields=+l` in it. Ctags reads this file by default (nothing to do with Gutentags) to get any default options you always want applied (see the Ctags documentation for more info).

Note that Gutentags also offers a per-project options file with the `.gutctags` file.

**Comment by tonywoode** [comment]
searching for an answer led me here, but I found this in your `.vimrc` will also work perfectly well:

```
let g:gutentags_ctags_extra_args = ['--fields=+l']
```
