### ISSUE TITLE
Docs outdated or lists outdated commands

### ISSUE THREAD

**Issue by wikimatze** [ludovicchabant/vim-gutentags#57]
Hi Ludovic,

thanks for the awesome plugin. It works for me without any configuration I've to made and it is very fast.

The following commands are not available:

- `:GutentagsGenerate`
- `:GutentagsToggleEnabled`
- `:GutentagsToggleTrace`
- `:GutentagsUnlock`

Maybe you can update the documentation.

**Comment by ludovicchabant** [comment]
I updated the documentation to remove `:GutentagsGenerate` since it is indeed gone. However the other 3 do exist, but it says in the documentation they're only enabled if you set `g:gutentags_define_advanced_commands` (since they're only for debugging).

**Comment by wikimatze** [comment]
Perfect, thanks for your help.
