### ISSUE TITLE
Error when starting vim outside of VCS controlled dir

### ISSUE THREAD

**Issue by KenjiTakahashi** [ludovicchabant/vim-gutentags#58]
When starting vim in a directory that is not under any VCS, it gives me
```
Error detected while processing function gutentags#setup_gutentags[35]..<SNR>113_cache_project_root:
line   17:
E713: Cannot use empty key for Dictionary
```

It, quite obviously, started happening after the https://github.com/ludovicchabant/vim-gutentags/commit/52a1f72819e08c4c16fb263b6d1d0c99983f339a commit.

**Comment by esran** [comment]
Interestingly, I was about to raise an issue with errors starting in a VCS directory:

Error detected while processing function gutentags#setup_gutentags[82]..<SNR>152_update_tags[33]..gutentags#ctags#generate:
line   66:
E499: Empty file name for '%' or '#', only works with ":p:h": !/home/sean/.vim/bundle/vim-gutentags/plat/unix/update_tags.sh -e "ctags" -t "/home/sean/.dotfiles
/tags" -p "/home/sean/.dotfiles" -o "/home/sean/.vim/bundle/vim-gutentags/res/ctags.options" -x "*.o" -x "*.obj" -x "*.exe" -x "*.so" -x "*.dll" -x "*.pyc" -x "
.svn" -x ".hg" -x ".bzr" -x ".git" -x ".sass-cache" -x "*.class" -x "*.scssc" -x "*.cssc" -x "sprockets%*" -x "*.lessc" -x "*/node_modules/*" -x "rake-pipeline-
*" -x "*/debian/*" -x "*/debian-*/*" > /dev/null 2>&1 &
Press ENTER or type command to continue
Error detected while processing function gutentags#setup_gutentags:
line   82:
E171: Missing :endif

**Comment by ludovicchabant** [comment]
Mmmh I can't repro... can both tell me more about the error? Does it show every time or just on some files?

**Comment by ludovicchabant** [comment]
Looking at the code, for the first error (the one reported by @KenjiTakahashi), it *could* happen if by chance there is a project root marker at the root of your file system (like a `/.git` file or folder). That would be quite weird, but I guess it's possible. Can you check if that's the case?

For the second error (@esran), first, it looks like you have a space in your cache directory? (`/home/sean/.dotfiles /tags`). Second, one of the excluded patterns is `sprockets%*`, is that correct? Looks like somehow the batch script is unhappy about it, maybe I need to escape that or something...

**Comment by esran** [comment]
The space is actually a cut&paste error on my part and is not actually there in the error. The `sprockets%*` is there though. Its in my `wildignore` variable setting. Removing that makes the error disappear. Thankyou!

**Comment by KenjiTakahashi** [comment]
Spot on! I've had a `/.svn` dir present and this caused the problem. I even know where it came from. When I was in Italy recently, I've had to use a USB shtick (by ONDA, FYI) to connect to the internet and I kinda felt it will turn messy. Their driver installer for OSX had files packaged along with **their SVN repo info** and it got installed into `/`... Damn, now I'll have to clean up this mess.
Anyway, your assumption was correct and thanks for revealing this to me!

**Comment by ludovicchabant** [comment]
I added a warning when Gutentags finds a project root marker at the root of the file-system, and it will disable Gutentags for those files, so that should solve one problem.
For the other problem I think I'm probably not escaping something correctly when passing arguments to the shell script... I'll close this bug for now though since I've got some script improvements coming.
Thanks!
