### ISSUE TITLE
still problems with spaces in path names on os x

### ISSUE THREAD

**Issue by nilsbecker** [ludovicchabant/vim-gutentags#65]
here is what i get when opening a file:
```
"~/Tresors/teaching/Frontiers in Biosciences/tutorial.tex" 356L, 13304C
Error detected while processing function gutentags#setup_gutentags[79]..<SNR>117_update_tags[33]..gutentags#ctags#generate:
line   17:
E344: Can't find directory "/Users/nbecker/Tresors/teaching/Frontiers_in_Biosciences" in cdpath
E472: Command failed
Error detected while processing function gutentags#setup_gutentags:
line   79:
E171: Missing :endif    
```

somehow underscores get inserted?! i have updated vim-gutentags just now, should be the current version. macvim, with vim 7.4.1362

**Comment by ludovicchabant** [comment]
Ah damn, sorry about that, I forgot to test without the cache directory (for when the `tags` file doesn't go in the project root). Should be fixed with 88e30ac9b94e115271c17c2b69ba470a12cd5524.
