### ISSUE TITLE
Indexing updated source truncates tag file

### ISSUE THREAD

**Issue by gezpage** [ludovicchabant/vim-gutentags#81]
I have been attempting to get gutentags to work on a PHP codebase, but have problems. 

Entering a project correctly generates a ~50MB tags file, jumping through functions and autocompleting using the tags works great. But when I call `:GutentagsUpdate` or save a file, the tags file becomes much smaller (around ~6Mb) and Vim complains with `E431: Format error in tags file` when I attempt to jump to a function definition again.

After attempting to debug the problem it appears that when `plat/unix/update_tags.sh` is called, it attempts to generate a temp tags file, but the `$UPDATED_SOURCE` value becomes `.../vim-gutentags/plat/unix/update_tags.sh` in the grep command (see https://github.com/ludovicchabant/vim-gutentags/blob/master/plat/unix/update_tags.sh#L77).

This means the temp file is blank and the `ctags --append` only populates it with the new content before replacing the old tags file.

Hope this makes sense. Any pointers on how to debug this further? Happy to help out.

Cheers.

**Comment by gezpage** [comment]
Found that grep was failing as it detected the tags file as binary. I still don't know why this is happening but adding the `-a` switch forces grep to treat the file as text, which resolves the issue.

**Comment by ludovicchabant** [comment]
Ah interesting. My guess is that maybe `ctags` is somehow indexing binary files, or source files with "unusual" character sets, so the `tags` file ends up with some symbols that contain characters that it interprets as binary?  However, I'm worried that using the `-a` switch messes up Unicode symbols... it's pretty unusual (most programming languages are ASCII only) but it can happen.

**Comment by ludovicchabant** [comment]
Ok I just merged a PR which adds the `--text` flag, which is the same a `-a`. Thanks!

**Comment by yevhen-m** [comment]
Updating tag file still truncates it for my event with `grep --text` command. What can be the issue?

**Comment by ludovicchabant** [comment]
No idea off the top of my head... :(

If you enable tracing (`:call gutentags#toggletrace()`) you will get a log file next to your tags file which shows what happened. This way you can run every step by hand in the command line and see at what point the tags file got truncated...

**Comment by yevhen-m** [comment]
Sorry, there was a problem with my ctags. Your plugin works smooth.
