### ISSUE TITLE
Enable vim-gutentags for specific folders only?

### ISSUE THREAD

**Issue by markwu** [ludovicchabant/vim-gutentags#82]
I always put my projects inside ~/Projects , ~/WWW, ~/Personal  .... only. Therefore, I have projects looks like

```
~/Project/proj1
~/Project/proj2
~/WWW/site1
~/WWW/site2
~/Personal/toy1
~/Personal/toy2
```

Is that possible to have a new global variable `g:gutentags_enabled_dirs` to control gutentags only works for those directories? It would be looks like

```vim
let g:gutentags_enabled_dirs = ['~/Project/', '~/WWW', '~/Personal']
```

Then, I don't need to create `.notags` for other projects outside `g:gutentags_enabled_dirs`. For example 

```
~/Outside/proj3
```
It will much easier to avoid gutentags generate tags accidentally like #13 said.
Reference:  #54, #74

**Comment by markwu** [comment]
Ok, I just try to implement this with `g:gutentags_enabled_user_func`, it works perfect. Here comes the result.

```vim
let g:gutentags_enabled_dirs = ['~/Projects', '~/WWW']
let g:gutentags_enabled_user_func = 'CheckEnabledDirs'

function! CheckEnabledDirs(file)
    let file_path = fnamemodify(a:file, ':p:h')
    for enabled_dir in g:gutentags_enabled_dirs
        let enabled_path = fnamemodify(enabled_dir, ':p:h')
        if match(enabled_path, file_path) == 0
            return 1
        else
            let gutentags_root = gutentags#get_project_root(file_path)
            if filereadable(gutentags_root . '/.withtags')
                return 1
            else
                return 0
            endif
        endif
    endfor
endfunction
```

Now, gutentags works inside g:gutentags_enabled_dirs only and also works outside those dirs with `.withtags` file.

**Comment by markwu** [comment]
I think these are two kinds of different strategies.

1. Original gutentags works like enabled for everything, but disabled for specific one with `.notags` and `g:gutentags_exclude_project_root` (from recent bitbucket repository)

2. I just want gutentags disabled for everything, but enabled for specific one with `.withtags` and `g:gutentags_enabled_dirs`

The later one is  just what I need.

Anyway, thanks for working this great plugin, I like it, it works perfectly in my current working environment with above settings.

Mark

**Comment by ludovicchabant** [comment]
Thanks!

So yes, right Gutentags is "always enabled except for.." (where "except" is defined by a couple of things you mentioned). In https://github.com/ludovicchabant/vim-gutentags/issues/74 we are discussing however adding customizable project root lookups, so you would be able to do it the other way, i.e. specify a function that only returns a valid root path for anything in your home project folders... I think that would fit your needs, so I'll close this one.
