### ISSUE TITLE
Disable for filetypes

### ISSUE THREAD

**Issue by magicalbanana** [ludovicchabant/vim-gutentags#88]
I am using vim-go already and it has it's own tag plugin. I was wondering if I can selectively disable this for certain file types, in this case go.

**Comment by ludovicchabant** [comment]
You can do this right now with `g:gutentags_enabled_user_func`, which is a callback function that gets passed the path to the current file, and is expected to return a boolean (`1` if Gutentags should run, `0` is the file should be ignored).

I only took a brief look at `vim-go` but if you're talking about their including Tagbar, that's pretty much complementary to gutentags -- Tagbar launches its own `ctags` process for the current file only.

Last thing, Gutentags also has some support to recognize different projects (Gutentags tries to work at the _project_ level, not the file level), and use different `ctags` executables. I don't know if gotags supports what Gutentags expects (the thing that's usually missing is the `--append` flag) but you could potentially also tell Gutentags to use Gotags for Go projects.

**Comment by magicalbanana** [comment]
I'm not too good with vim script, do you think you can show me a sample function I can modify to get my desired behaviour?

**Comment by ludovicchabant** [comment]
I would look like this roughly, in your `vimrc`:

```
function! MyCustomGutentagsEnableFunc(path) abort
    return fnamemodify(a:path, ':e') != 'go'
endfunction

let g:gutentags_enabled_user_func = 'MyCustomGutentagsEnableFunc'
```
