### ISSUE TITLE
temporary tags file into cache dir

### ISSUE THREAD

**Issue by Konfekt** [ludovicchabant/vim-gutentags#9]
Hey, thanks for the closure that gutentags brought to us Vim taggers.

How about generating the temporary tag files, such as `tags.lock`, into ta `$XDG_CACHE_HOME/tags` folder ? (If set up by the user.)

While there are good reasons to leave the tag files in the project root, I don't see many for the temporary tag files.

**Comment by evaryont** [comment]
Using the `$TMP` or `$TMPDIR` environment variables might be enough for most OS's. (While still allowing an override via `g:gutentags_cache_dir`.)

**Comment by Konfekt** [comment]
The temp paths are listed in the default value `set backupskip&?`.

**Comment by ludovicchabant** [comment]
Mmmh `backupskip` only lists file patterns... I'd have to parse that to remove the wildcards and stuff... did you mean `backupdir`?

**Comment by Konfekt** [comment]
Hmm, true that these are Vim file patterns. that's why I asked about https://groups.google.com/forum/m/#!topic/vim_use/NXFksN223bc

But it's rather meant as inspiration regading the system's default temp folder. It defaults to
```vim
'backupskip' 'bsk'	string	(default: "/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*")
```

**Comment by ludovicchabant** [comment]
I thought about this thing some more and I prefer keeping the temp files next to the tags file. When it goes well, you don't notice anything, and when it goes bad, it makes it a lot easier to cleanup or troubleshoot stuff (finding a specific file in the OS's temp dirs is really painful).

Of course, if anybody with more free time than me want to submit a pull request that adds the option, I'll gladly merge it, but in the meantime I'll close this.

**Comment by Konfekt** [comment]
Okay, to achieve that using `tempname()` instead of `.tags.temp` should suffice.
