### ISSUE TITLE
ctags options

### ISSUE THREAD

**Issue by vaxXxa** [ludovicchabant/vim-gutentags#94]
How can with I run `vim-gutentags` my custom command, like this:
`ctags --languages=python --python-kinds=-iv -R` ?

**Comment by ludovicchabant** [comment]
You can make use of `ctags`' configuration files... if you want those options for *all* projects, you can add them to your `~/.ctags`. If you want those options only for a specific project, you can add them to a `.gutctags` file at the root of said project.

Check the `ctags` documentation for more info on configuration files... but basically you put each option on a separate line.
