### ISSUE TITLE
Gotcha running vim-gutentags in OSX.

### ISSUE THREAD

**Issue by nnathan** [ludovicchabant/vim-gutentags#96]
Apparently XCode installs a stripped down BSD version of ctags.

I battled for a good 30 mins trying to understand why vim-gutentags simply wasn't working.

I think there should be a note in documentation and README that gutentags depends specifically on [exuberant-ctags](http://ctags.sourceforge.net/), and will not work with BSD ctags which is shipped in OSX and BSD variants. Well something to that effect.

**Comment by ludovicchabant** [comment]
Done! Thanks.
