### ISSUE TITLE
Can't stop gutentags error message on version<704

### ISSUE THREAD

**Issue by cmcaine** [ludovicchabant/vim-gutentags#98]
I keep my vim config in dotfiles and have the misfortune of occasionally using really old machines.

Expected behaviour:
`let g:gutentags_enabled=0` or `let g:loaded_gutentags = 1` should stop gutentags from loading before the error message appears.

Actual behaviour:
`plugin/gutentags.vim` issues the warning regardless of the status of those variables.

**Comment by ludovicchabant** [comment]
`g:gutentags_enabled` will just make Gutentags temporarily not regenerate the tags files -- but it's still loaded. And I want to keep `g:loaded_gutentags` as something internal in case I need it to check some state...

So with 9db76feab6c244f2859091953fda9b4763914e3c I added `g:gutentags_dont_load` which should do what you need. Note that I would recommend instead that you use some plugin manager like Pathogen or Vundle, and that, in a machine-local config file, you tell that plugin manager to not load plugins from certain paths. This will probably be more efficient than making sure all plugins support a way to suppress loading.

**Comment by cmcaine** [comment]
You're right: `g:pathogen_blacklist` would be a more elegant way to do this.

I just looked for the same method used to disable other vim stuff.

**Comment by cmcaine** [comment]
Thanks for the commit, though :)
